#### notes:
# use the `=LOWER(B1)` command in excel to convert the contents of the A1 to lowercase


### Convert all filenames to lowercase
for i in $( ls | grep [A-Z] ); do mv -i $i `echo $i | tr 'A-Z' 'a-z'`; done

### name overrides for game root
mv audio Audio
mv chars Chars
mv cut Cut
mv levels Levels
mv movies Movies
mv pc PC
mv scripts Scripts
mv stuff Stuff
mv binkw32.dll BinkW32.dll

### Audio folder
cd Audio
mv _cutscenes _CutScenes
mv _music _Music
mv _soundfx _SoundFX
cd .. #return to root

### Audio\_CutScenes
cd Audio\_CutScenes
mv asteroidchase_intro.ogg AsteroidChase_Intro.ogg
mv asteroidchase_midtro.ogg AsteroidChase_Midtro.ogg
mv asteroidchase_outro.ogg AsteroidChase_Outro.ogg
mv blockaderunner_intro.ogg BlockadeRunner_Intro.ogg
mv blockaderunner_midtro.ogg BlockadeRunner_Midtro.ogg
mv blockaderunner_outro.ogg BlockadeRunner_Outro.ogg
mv blockaderunner_outroa.ogg BlockadeRunner_OutroA.ogg
mv cloudcityescape_intro.ogg CloudCityEscape_Intro.ogg
mv cloudcityescape_midtro.ogg CloudCityEscape_Midtro.ogg
mv cloudcityescape_outro.ogg CloudCityEscape_Outro.ogg
mv cloudcitytrapoutro.ogg CloudCityTrapOutro.ogg
mv cloudcitytrap_intro.ogg CloudCityTrap_Intro.ogg
mv dagobah_intro.ogg Dagobah_Intro.ogg
mv dagobah_midtro1.ogg Dagobah_Midtro1.ogg
mv dagobah_midtro2.ogg Dagobah_Midtro2.ogg
mv dagobah_outro.ogg Dagobah_Outro.ogg
mv deathstar2battle_intro.ogg DeathStar2Battle_Intro.ogg
mv deathstar2battle_midtro.ogg DeathStar2Battle_Midtro.ogg
mv deathstar2battle_outro.ogg DeathStar2Battle_Outro.ogg
mv deathstarbattle_intro.ogg DeathStarBattle_Intro.ogg
mv deathstarbattle_midtro.ogg DeathStarBattle_Midtro.ogg
mv deathstarbattle_midtro_inga.ogg DeathStarBattle_Midtro_IngA.ogg
mv deathstarbattle_outro.ogg DeathStarBattle_Outro.ogg
mv deathstarescape_intro.ogg DeathStarEscape_Intro.ogg
mv deathstarescape_outro.ogg DeathStarEscape_Outro.ogg
mv deathstarrescueoutro.ogg DeathStarRescueOutro.ogg
mv deathstarrescue_intro.ogg DeathStarRescue_Intro.ogg
mv deathstarrescue_midtro.ogg DeathStarRescue_Midtro.ogg
mv emperorfight_intro.ogg EmperorFight_Intro.ogg
mv emperorfight_outro.ogg EmperorFight_Outro.ogg
mv endorbattle_intro.ogg EndorBattle_Intro.ogg
mv endorbattle_outro.ogg EndorBattle_Outro.ogg
mv ep1_anakinpodexplode.ogg Ep1_AnakinPodExplode.ogg
mv ep1_anisflightintro.ogg Ep1_AnisFlightIntro.ogg
mv ep1_anisflightoutro.ogg Ep1_AnisFlightOutro.ogg
mv ep1_complete.ogg Ep1_Complete.ogg
mv ep1_darthmaulintro.ogg Ep1_DarthMaulIntro.ogg
mv ep1_darthmauloutro.ogg Ep1_DarthMaulOutro.ogg
mv ep1_failednegintro.ogg Ep1_FailedNegIntro.ogg
mv ep1_failednegoutro.ogg Ep1_FailedNegOutro.ogg
mv ep1_gungancityintro.ogg Ep1_GunganCityIntro.ogg
mv ep1_gungancityoutro.ogg Ep1_GunganCityOutro.ogg
mv ep1_invnaboooutro.ogg Ep1_InvNabooOutro.ogg
mv ep1_mawhoniccrash.ogg Ep1_MawhonicCrash.ogg
mv ep1_podraceintro.ogg Ep1_PodraceIntro.ogg
mv ep1_podraceoutro.ogg Ep1_PodraceOutro.ogg
mv ep1_podrace_outoftime.ogg Ep1_Podrace_Outoftime.ogg
mv ep1_podrace_podexplode.ogg Ep1_Podrace_Podexplode.ogg
mv ep1_podrace_sebulba.ogg Ep1_Podrace_Sebulba.ogg
mv ep1_podrace_tusken.ogg Ep1_Podrace_Tusken.ogg
mv ep1_rescueqn_intro.ogg Ep1_RescueQn_Intro.ogg
mv ep1_rescueqn_outro.ogg Ep1_RescueQn_Outro.ogg
mv ep1_retakeplc_intro.ogg Ep1_RetakePlc_Intro.ogg
mv ep1_retakeplc_outro.ogg Ep1_RetakePlc_Outro.ogg
mv ep2_bountyhunterpursuit.ogg Ep2_BountyHunterPursuit.ogg
mv ep2_discoverjango.ogg Ep2_DiscoverJango.ogg
mv ep2_dookufight.ogg Ep2_Dookufight.ogg
mv ep2_dookuintro.ogg Ep2_DookuIntro.ogg
mv ep2_dookuoutro.ogg Ep2_DookuOutro.ogg
mv ep2_dookuyodaarr.ogg Ep2_DookuYodaArr.ogg
mv ep2_droidfactintro.ogg Ep2_DroidFactIntro.ogg
mv ep2_droidfactoutro.ogg Ep2_DroidFactOutro.ogg
mv ep2_gunshipcavintro.ogg Ep2_GunshipCavIntro.ogg
mv ep2_gunshipcavminids.ogg Ep2_GunshipCavminids.ogg
mv ep2_gunshipcavoutro.ogg Ep2_GunshipCavOutro.ogg
mv ep2_gunshipexplode.ogg Ep2_GunshipExplode.ogg
mv ep2_jangointro.ogg Ep2_JangoIntro.ogg
mv ep2_jangomines.ogg Ep2_JangoMines.ogg
mv ep2_jedibattleintro.ogg Ep2_JediBattleIntro.ogg
mv ep2_jedibattlemid.ogg Ep2_JediBattleMid.ogg
mv ep2_jedibattleoutro.ogg Ep2_JediBattleOutro.ogg
mv ep2_kaminointro.ogg Ep2_KaminoIntro.ogg
mv ep2_kaminomidtro.ogg Ep2_KaminoMidtro.ogg
mv ep2_kaminooutro.ogg Ep2_KaminoOutro.ogg
mv ep2_kaminorevealclones.ogg Ep2_KaminoRevealClones.ogg
mv ep2_outro.ogg Ep2_Outro.ogg
mv ep2_pursuit_intro.ogg Ep2_Pursuit_Intro.ogg
mv ep2_pursuit_midtro1.ogg Ep2_Pursuit_Midtro1.ogg
mv ep2_pursuit_midtro2.ogg Ep2_Pursuit_Midtro2.ogg
mv ep2_pursuit_outro.ogg Ep2_Pursuit_Outro.ogg
mv ep3_cruiserdefeatdooku.ogg Ep3_CruiserDefeatDooku.ogg
mv ep3_cruiserenterdooku.ogg Ep3_CruiserEnterDooku.ogg
mv ep3_cruiserintro.ogg Ep3_CruiserIntro.ogg
mv ep3_cruisermeetgrev.ogg Ep3_CruiserMeetGrev.ogg
mv ep3_cruiseroutro.ogg Ep3_CruiserOutro.ogg
mv ep3_dogfightdie.ogg Ep3_DogFightDie.ogg
mv ep3_dogfightintro.ogg Ep3_DogFightIntro.ogg
mv ep3_dogfightoutro.ogg Ep3_DogFightOutro.ogg
mv ep3_grevintro.ogg Ep3_GrevIntro.ogg
mv ep3_grevoutro.ogg Ep3_GrevOutro.ogg
mv ep3_kashintro.ogg Ep3_KashIntro.ogg
mv ep3_kashorder66.ogg Ep3_KashOrder66.ogg
mv ep3_kashoutro.ogg Ep3_KashOutro.ogg
mv ep3_outro.ogg Ep3_Outro.ogg
mv ep3_ruinintro.ogg Ep3_RuinIntro.ogg
mv ep3_ruinoutro.ogg Ep3_RuinOutro.ogg
mv ep3_vaderfight1.ogg Ep3_VaderFight1.ogg
mv ep3_vaderfight2.ogg Ep3_VaderFight2.ogg
mv ep3_vaderintro.ogg Ep3_VaderIntro.ogg
mv ep3_vaderoutroextended.ogg Ep3_VaderOutroExtended.ogg
mv ep3_vaderoutroshort.ogg Ep3_VaderOutroShort.ogg
mv ep4_anewhopeintro.ogg Ep4_ANewHopeIntro.ogg
mv ep4_anewhopeoutro.ogg Ep4_ANewHopeOutro.ogg
mv episode4ending.ogg Episode4Ending.ogg
mv episode5ending.ogg Episode5Ending.ogg
mv episode6_ending.ogg Episode6_Ending.ogg
mv hothbattle_intro.ogg HothBattle_Intro.ogg
mv hothbattle_outro.ogg HothBattle_Outro.ogg
mv hothescape_intro.ogg HothEscape_Intro.ogg
mv hothescape_outro.ogg HothEscape_Outro.ogg
mv ij_losttemple_intro.ogg IJ_LostTemple_Intro.ogg
mv ij_losttemple_midtro.ogg IJ_LostTemple_Midtro.ogg
mv ij_losttemple_outrolose.ogg IJ_LostTemple_OutroLose.ogg
mv ij_losttemple_outrowwin.ogg IJ_LostTemple_OutrowWin.ogg
mv jabbaspalace_intro.ogg JabbasPalace_Intro.ogg
mv jabbaspalace_midtro1.ogg JabbasPalace_Midtro1.ogg
mv jabbaspalace_midtro2.ogg JabbasPalace_Midtro2.ogg
mv jabbaspalace_outro.ogg JabbasPalace_Outro.ogg
mv moseisley_intro.ogg MosEisley_Intro.ogg
mv moseisley_midtro.ogg MosEisley_Midtro.ogg
mv moseisley_outro.ogg MosEisley_Outro.ogg
mv sarlaccpit_intro.ogg SarlaccPit_Intro.ogg
mv sarlaccpit_midtro.ogg SarlaccPit_Midtro.ogg
mv sarlaccpit_midtro2.ogg SarlaccPit_Midtro2.ogg
mv sarlaccpit_outro.ogg SarlaccPit_Outro.ogg
mv speederchase_intro.ogg SpeederChase_Intro.ogg
mv speederchase_outro.ogg SpeederChase_Outro.ogg
mv tatooine_intro.ogg Tatooine_Intro.ogg
mv tatooine_outro.ogg Tatooine_Outro.ogg
cd ..\..

### Audio\_Music
cd Audio\_Music
mv act_astchase_abc.ogg Act_AstChase_ABC.ogg
mv act_astchase_cave.ogg Act_AstChase_Cave.ogg
mv act_astchase_d.ogg Act_AstChase_D.ogg
mv act_bonus.ogg Act_Bonus.ogg
mv act_br_tantive.ogg Act_BR_Tantive.ogg
mv act_cc_escape_a.ogg Act_CC_Escape_A.ogg
mv act_cc_escape_bc.ogg Act_CC_Escape_BC.ogg
mv act_cc_trap.ogg Act_CC_Trap.ogg
mv act_dagobah_abce.ogg Act_Dagobah_ABCE.ogg
mv act_dagobah_d.ogg Act_Dagobah_D.ogg
mv act_ds2b_a.ogg Act_DS2B_A.ogg
mv act_ds2b_bc.ogg Act_DS2B_BC.ogg
mv act_ds2b_d.ogg Act_DS2B_D.ogg
mv act_ds2b_efg.ogg Act_DS2B_EFG.ogg
mv act_dsb_appr.ogg Act_DSB_Appr.ogg
mv act_dsb_shieldgone.ogg Act_DSB_ShieldGone.ogg
mv act_dsb_trench.ogg Act_DSB_Trench.ogg
mv act_ds_escape.ogg Act_DS_Escape.ogg
mv act_ds_rescue.ogg Act_DS_Rescue.ogg
mv act_emperorfight.ogg Act_EmperorFight.ogg
mv act_endorbattle_abc.ogg Act_EndorBattle_Abc.ogg
mv act_endorbattle_d.ogg Act_EndorBattle_D.ogg
mv act_gamorrdisco.ogg Act_GamorrDisco.ogg
mv act_hothbattle_acde.ogg Act_HothBattle_ACDE.ogg
mv act_hothbattle_b.ogg Act_HothBattle_B.ogg
mv act_hothescape_abc.ogg Act_HothEscape_Abc.ogg
mv act_hothescape_d.ogg Act_HothEscape_D.ogg
mv act_jabbas_a.ogg Act_Jabbas_A.ogg
mv act_jabbas_bd.ogg Act_Jabbas_Bd.ogg
mv act_jabbas_e.ogg Act_Jabbas_E.ogg
mv act_mosalley.ogg Act_MosAlley.ogg
mv act_moscant.ogg Act_MosCant.ogg
mv act_moshangar.ogg Act_MosHangar.ogg
mv act_mos_a.ogg Act_Mos_A.ogg
mv act_mos_b.ogg Act_Mos_B.ogg
mv act_sarlacc_a.ogg Act_Sarlacc_A.ogg
mv act_sarlacc_b.ogg Act_Sarlacc_B.ogg
mv act_sarlacc_c.ogg Act_Sarlacc_C.ogg
mv act_speederchase.ogg Act_SpeederChase.ogg
mv act_tatooine.ogg Act_Tatooine.ogg
mv act_tatooine_b.ogg Act_Tatooine_B.ogg
mv amb_astchase_cave.ogg Amb_AstChase_Cave.ogg
mv amb_bonus.ogg Amb_Bonus.ogg
mv amb_br_tantive.ogg Amb_BR_Tantive.ogg
mv amb_cc_escape_bc.ogg Amb_CC_Escape_BC.ogg
mv amb_cc_trap.ogg Amb_CC_Trap.ogg
mv amb_dagobah_abce.ogg Amb_Dagobah_ABCE.ogg
mv amb_dagobah_d.ogg Amb_Dagobah_D.ogg
mv amb_dsb.ogg Amb_DSB.ogg
mv amb_dsb_int.ogg Amb_DSB_Int.ogg
mv amb_ds_escape.ogg Amb_DS_Escape.ogg
mv amb_ds_rescue.ogg Amb_DS_Rescue.ogg
mv amb_endorbunker.ogg Amb_EndorBunker.ogg
mv amb_endorforest.ogg Amb_EndorForest.ogg
mv amb_hothbattle_acde.ogg Amb_HothBattle_ACDE.ogg
mv amb_hothbattle_b.ogg Amb_HothBattle_B.ogg
mv amb_hothescape_d.ogg Amb_HothEscape_D.ogg
mv amb_jabbas_bde.ogg Amb_Jabbas_BDE.ogg
mv amb_legocities.ogg Amb_LegoCities.ogg
mv amb_mos.ogg Amb_Mos.ogg
mv amb_mosalley.ogg Amb_Mosalley.ogg
mv amb_moscant.ogg Amb_Moscant.ogg
mv amb_moshangar.ogg Amb_Moshangar.ogg
mv amb_tatooine.ogg Amb_Tatooine.ogg
mv amb_tatooine_b.ogg Amb_Tatooine_B.ogg
mv credits2m.ogg Credits2M.ogg
mv dexinside.ogg DexInside.ogg
mv dexinside_ambience.ogg DexInside_Ambience.ogg
mv dexoutside.ogg DexOutside.ogg
mv dexoutside_ambience.ogg DexOutside_Ambience.ogg
mv ep1_1_action.ogg Ep1_1_Action.ogg
mv ep1_1_ambience.ogg Ep1_1_Ambience.ogg
mv ep1_1_quiet.ogg Ep1_1_Quiet.ogg
mv ep1_2_action.ogg Ep1_2_Action.ogg
mv ep1_2_ambience.ogg Ep1_2_Ambience.ogg
mv ep1_2_quiet.ogg Ep1_2_Quiet.ogg
mv ep1_3_action.ogg Ep1_3_Action.ogg
mv ep1_3_ambience.ogg Ep1_3_Ambience.ogg
mv ep1_3_quiet.ogg Ep1_3_Quiet.ogg
mv ep1_4_action.ogg Ep1_4_Action.ogg
mv ep1_4_ambience.ogg Ep1_4_Ambience.ogg
mv ep1_5_action.ogg Ep1_5_Action.ogg
mv ep1_5_ambience.ogg Ep1_5_Ambience.ogg
mv ep1_5_quiet.ogg Ep1_5_Quiet.ogg
mv ep1_7_action.ogg Ep1_7_Action.ogg
mv ep1_7_ambience.ogg Ep1_7_Ambience.ogg
mv ep1_7_quiet.ogg Ep1_7_Quiet.ogg
mv ep1_anakinsflight_action.ogg Ep1_AnakinsFlight_Action.ogg
mv ep1_anakinsflight_ambience.ogg Ep1_AnakinsFlight_Ambience.ogg
mv ep1_endcredits.ogg Ep1_EndCredits.ogg
mv ep1_textcrawl.ogg Ep1_TextCrawl.ogg
mv ep2_1_actiona_f.ogg Ep2_1_ActionA_F.ogg
mv ep2_1_actionb_e.ogg Ep2_1_ActionB_E.ogg
mv ep2_1_ambiencea_f.ogg Ep2_1_AmbienceA_F.ogg
mv ep2_1_ambienceb_e.ogg Ep2_1_AmbienceB_E.ogg
mv ep2_1_bhp_action.ogg Ep2_1_BHP_Action.ogg
mv ep2_1_bhp_ambience.ogg Ep2_1_BHP_Ambience.ogg
mv ep2_1_quieta_f.ogg Ep2_1_QuietA_F.ogg
mv ep2_1_quietb_e.ogg Ep2_1_QuietB_E.ogg
mv ep2_1_starwarsdisco.ogg Ep2_1_StarWarsDisco.ogg
mv ep2_2_action.ogg Ep2_2_Action.ogg
mv ep2_2_ambience.ogg Ep2_2_Ambience.ogg
mv ep2_2_quiet.ogg Ep2_2_Quiet.ogg
mv ep2_3_action.ogg Ep2_3_Action.ogg
mv ep2_3_ambience.ogg Ep2_3_Ambience.ogg
mv ep2_4_action.ogg Ep2_4_Action.ogg
mv ep2_4_ambience.ogg Ep2_4_Ambience.ogg
mv ep2_5_action.ogg Ep2_5_Action.ogg
mv ep2_5_ambience.ogg Ep2_5_Ambience.ogg
mv ep2_5_quiet.ogg Ep2_5_Quiet.ogg
mv ep2_endcredits.ogg Ep2_EndCredits.ogg
mv ep2_textcrawl.ogg Ep2_TextCrawl.ogg
mv ep3_1_action.ogg Ep3_1_Action.ogg
mv ep3_1_ambience.ogg Ep3_1_Ambience.ogg
mv ep3_2_action.ogg Ep3_2_Action.ogg
mv ep3_2_ambience.ogg Ep3_2_Ambience.ogg
mv ep3_2_quiet.ogg Ep3_2_Quiet.ogg
mv ep3_3_action.ogg Ep3_3_Action.ogg
mv ep3_3_ambience.ogg Ep3_3_Ambience.ogg
mv ep3_4_action.ogg Ep3_4_Action.ogg
mv ep3_4_ambience.ogg Ep3_4_Ambience.ogg
mv ep3_4_quiet.ogg Ep3_4_Quiet.ogg
mv ep3_5_action.ogg Ep3_5_Action.ogg
mv ep3_5_ambience.ogg Ep3_5_Ambience.ogg
mv ep3_5_quiet.ogg Ep3_5_Quiet.ogg
mv ep3_6_action.ogg Ep3_6_Action.ogg
mv ep3_6_ambience.ogg Ep3_6_Ambience.ogg
mv ep3_endcredits.ogg Ep3_EndCredits.ogg
mv ep3_textcrawl.ogg Ep3_TextCrawl.ogg
mv ep4_bonus_action.ogg Ep4_Bonus_Action.ogg
mv ep4_bonus_ambience.ogg Ep4_Bonus_Ambience.ogg
mv ep4_bonus_quiet.ogg Ep4_Bonus_Quiet.ogg
mv ep4_endcredits.ogg Ep4_EndCredits.ogg
mv ep4_textcrawl.ogg Ep4_TextCrawl.ogg
mv ep5_endcredits.ogg Ep5_EndCredits.ogg
mv ep5_textcrawl.ogg Ep5_TextCrawl.ogg
mv ep6_endcredits.ogg Ep6_EndCredits.ogg
mv ep6_textcrawl.ogg Ep6_TextCrawl.ogg
mv ij_act_level1.ogg IJ_Act_Level1.ogg
mv ij_act_level2.ogg IJ_Act_Level2.ogg
mv ij_act_level3.ogg IJ_Act_Level3.ogg
mv ij_amb_level1.ogg IJ_Amb_Level1.ogg
mv ij_amb_placeholder.ogg IJ_Amb_Placeholder.ogg
mv ij_credits.ogg IJ_Credits.ogg
mv ij_gameover.ogg IJ_GameOver.ogg
mv ij_qui_level1.ogg IJ_Qui_Level1.ogg
mv ij_qui_level2.ogg IJ_Qui_Level2.ogg
mv ij_qui_level3.ogg IJ_Qui_Level3.ogg
mv ij_titles.ogg IJ_Titles.ogg
mv qui_bonus.ogg Qui_Bonus.ogg
mv qui_br_tantive.ogg Qui_BR_Tantive.ogg
mv qui_cc_escape_a.ogg Qui_CC_Escape_A.ogg
mv qui_cc_escape_bc.ogg Qui_CC_Escape_BC.ogg
mv qui_cc_trap.ogg Qui_CC_Trap.ogg
mv qui_dagobah_abce.ogg Qui_Dagobah_ABCE.ogg
mv qui_dagobah_d.ogg Qui_Dagobah_D.ogg
mv qui_ds_escape.ogg Qui_DS_Escape.ogg
mv qui_ds_rescue.ogg Qui_DS_Rescue.ogg
mv qui_emperorfight.ogg Qui_EmperorFight.ogg
mv qui_endorbattle_abc.ogg Qui_EndorBattle_ABC.ogg
mv qui_endorbattle_d.ogg Qui_EndorBattle_D.ogg
mv qui_hothescape_abc.ogg Qui_HothEscape_Abc.ogg
mv qui_hothescape_d.ogg Qui_HothEscape_D.ogg
mv qui_jabbas_a.ogg Qui_Jabbas_A.ogg
mv qui_jabbas_bd.ogg Qui_Jabbas_BD.ogg
mv qui_legocities.ogg Qui_LegoCities.ogg
mv qui_mosalley.ogg Qui_MosAlley.ogg
mv qui_moscant1.ogg Qui_MosCant1.ogg
mv qui_moscant2.ogg Qui_MosCant2.ogg
mv qui_moshangar.ogg Qui_MosHangar.ogg
mv qui_mos_a.ogg Qui_Mos_A.ogg
mv qui_mos_b.ogg Qui_Mos_B.ogg
mv qui_sarlacc_b.ogg Qui_Sarlacc_B.ogg
mv qui_speederchase.ogg Qui_SpeederChase.ogg
mv qui_tatooine.ogg Qui_Tatooine.ogg
mv qui_tatooine_b.ogg Qui_Tatooine_B.ogg
mv statusscreen.ogg StatusScreen.ogg
mv titles.ogg Titles.ogg

cd ..\..

### Audio\_SoundFX\*
cd Audio\_SoundFX

cd ..\.. 