:::::::: notes:
:: use the `=LOWER(B1)` command in excel to convert the contents of the A1 to lowercase


:::::: Convert all filenames to lowercase (https://superuser.com/a/1103766)
for /r %%D in (.) do @for /f "eol=: delims=" %%F in ('dir /l/b "%%D"') do @ren "%%D\%%F" "%%F"

:::::: name overrides for game root
ren audio Audio
ren chars Chars
ren cut Cut
ren levels Levels
ren movies Movies
ren pc PC
ren scripts Scripts
ren stuff Stuff
ren binkw32.dll BinkW32.dll

:::::: Audio folder
cd Audio
ren _cutscenes _CutScenes
ren _music _Music
ren _soundfx _SoundFX
::return to root
cd .. 

:::::: Audio\_CutScenes
cd Audio\_CutScenes
ren asteroidchase_intro.ogg AsteroidChase_Intro.ogg
ren asteroidchase_midtro.ogg AsteroidChase_Midtro.ogg
ren asteroidchase_outro.ogg AsteroidChase_Outro.ogg
ren blockaderunner_intro.ogg BlockadeRunner_Intro.ogg
ren blockaderunner_midtro.ogg BlockadeRunner_Midtro.ogg
ren blockaderunner_outro.ogg BlockadeRunner_Outro.ogg
ren blockaderunner_outroa.ogg BlockadeRunner_OutroA.ogg
ren cloudcityescape_intro.ogg CloudCityEscape_Intro.ogg
ren cloudcityescape_midtro.ogg CloudCityEscape_Midtro.ogg
ren cloudcityescape_outro.ogg CloudCityEscape_Outro.ogg
ren cloudcitytrapoutro.ogg CloudCityTrapOutro.ogg
ren cloudcitytrap_intro.ogg CloudCityTrap_Intro.ogg
ren dagobah_intro.ogg Dagobah_Intro.ogg
ren dagobah_midtro1.ogg Dagobah_Midtro1.ogg
ren dagobah_midtro2.ogg Dagobah_Midtro2.ogg
ren dagobah_outro.ogg Dagobah_Outro.ogg
ren deathstar2battle_intro.ogg DeathStar2Battle_Intro.ogg
ren deathstar2battle_midtro.ogg DeathStar2Battle_Midtro.ogg
ren deathstar2battle_outro.ogg DeathStar2Battle_Outro.ogg
ren deathstarbattle_intro.ogg DeathStarBattle_Intro.ogg
ren deathstarbattle_midtro.ogg DeathStarBattle_Midtro.ogg
ren deathstarbattle_midtro_inga.ogg DeathStarBattle_Midtro_IngA.ogg
ren deathstarbattle_outro.ogg DeathStarBattle_Outro.ogg
ren deathstarescape_intro.ogg DeathStarEscape_Intro.ogg
ren deathstarescape_outro.ogg DeathStarEscape_Outro.ogg
ren deathstarrescueoutro.ogg DeathStarRescueOutro.ogg
ren deathstarrescue_intro.ogg DeathStarRescue_Intro.ogg
ren deathstarrescue_midtro.ogg DeathStarRescue_Midtro.ogg
ren emperorfight_intro.ogg EmperorFight_Intro.ogg
ren emperorfight_outro.ogg EmperorFight_Outro.ogg
ren endorbattle_intro.ogg EndorBattle_Intro.ogg
ren endorbattle_outro.ogg EndorBattle_Outro.ogg
ren ep1_anakinpodexplode.ogg Ep1_AnakinPodExplode.ogg
ren ep1_anisflightintro.ogg Ep1_AnisFlightIntro.ogg
ren ep1_anisflightoutro.ogg Ep1_AnisFlightOutro.ogg
ren ep1_complete.ogg Ep1_Complete.ogg
ren ep1_darthmaulintro.ogg Ep1_DarthMaulIntro.ogg
ren ep1_darthmauloutro.ogg Ep1_DarthMaulOutro.ogg
ren ep1_failednegintro.ogg Ep1_FailedNegIntro.ogg
ren ep1_failednegoutro.ogg Ep1_FailedNegOutro.ogg
ren ep1_gungancityintro.ogg Ep1_GunganCityIntro.ogg
ren ep1_gungancityoutro.ogg Ep1_GunganCityOutro.ogg
ren ep1_invnaboooutro.ogg Ep1_InvNabooOutro.ogg
ren ep1_mawhoniccrash.ogg Ep1_MawhonicCrash.ogg
ren ep1_podraceintro.ogg Ep1_PodraceIntro.ogg
ren ep1_podraceoutro.ogg Ep1_PodraceOutro.ogg
ren ep1_podrace_outoftime.ogg Ep1_Podrace_Outoftime.ogg
ren ep1_podrace_podexplode.ogg Ep1_Podrace_Podexplode.ogg
ren ep1_podrace_sebulba.ogg Ep1_Podrace_Sebulba.ogg
ren ep1_podrace_tusken.ogg Ep1_Podrace_Tusken.ogg
ren ep1_rescueqn_intro.ogg Ep1_RescueQn_Intro.ogg
ren ep1_rescueqn_outro.ogg Ep1_RescueQn_Outro.ogg
ren ep1_retakeplc_intro.ogg Ep1_RetakePlc_Intro.ogg
ren ep1_retakeplc_outro.ogg Ep1_RetakePlc_Outro.ogg
ren ep2_bountyhunterpursuit.ogg Ep2_BountyHunterPursuit.ogg
ren ep2_discoverjango.ogg Ep2_DiscoverJango.ogg
ren ep2_dookufight.ogg Ep2_Dookufight.ogg
ren ep2_dookuintro.ogg Ep2_DookuIntro.ogg
ren ep2_dookuoutro.ogg Ep2_DookuOutro.ogg
ren ep2_dookuyodaarr.ogg Ep2_DookuYodaArr.ogg
ren ep2_droidfactintro.ogg Ep2_DroidFactIntro.ogg
ren ep2_droidfactoutro.ogg Ep2_DroidFactOutro.ogg
ren ep2_gunshipcavintro.ogg Ep2_GunshipCavIntro.ogg
ren ep2_gunshipcavminids.ogg Ep2_GunshipCavminids.ogg
ren ep2_gunshipcavoutro.ogg Ep2_GunshipCavOutro.ogg
ren ep2_gunshipexplode.ogg Ep2_GunshipExplode.ogg
ren ep2_jangointro.ogg Ep2_JangoIntro.ogg
ren ep2_jangomines.ogg Ep2_JangoMines.ogg
ren ep2_jedibattleintro.ogg Ep2_JediBattleIntro.ogg
ren ep2_jedibattlemid.ogg Ep2_JediBattleMid.ogg
ren ep2_jedibattleoutro.ogg Ep2_JediBattleOutro.ogg
ren ep2_kaminointro.ogg Ep2_KaminoIntro.ogg
ren ep2_kaminomidtro.ogg Ep2_KaminoMidtro.ogg
ren ep2_kaminooutro.ogg Ep2_KaminoOutro.ogg
ren ep2_kaminorevealclones.ogg Ep2_KaminoRevealClones.ogg
ren ep2_outro.ogg Ep2_Outro.ogg
ren ep2_pursuit_intro.ogg Ep2_Pursuit_Intro.ogg
ren ep2_pursuit_midtro1.ogg Ep2_Pursuit_Midtro1.ogg
ren ep2_pursuit_midtro2.ogg Ep2_Pursuit_Midtro2.ogg
ren ep2_pursuit_outro.ogg Ep2_Pursuit_Outro.ogg
ren ep3_cruiserdefeatdooku.ogg Ep3_CruiserDefeatDooku.ogg
ren ep3_cruiserenterdooku.ogg Ep3_CruiserEnterDooku.ogg
ren ep3_cruiserintro.ogg Ep3_CruiserIntro.ogg
ren ep3_cruisermeetgrev.ogg Ep3_CruiserMeetGrev.ogg
ren ep3_cruiseroutro.ogg Ep3_CruiserOutro.ogg
ren ep3_dogfightdie.ogg Ep3_DogFightDie.ogg
ren ep3_dogfightintro.ogg Ep3_DogFightIntro.ogg
ren ep3_dogfightoutro.ogg Ep3_DogFightOutro.ogg
ren ep3_grevintro.ogg Ep3_GrevIntro.ogg
ren ep3_grevoutro.ogg Ep3_GrevOutro.ogg
ren ep3_kashintro.ogg Ep3_KashIntro.ogg
ren ep3_kashorder66.ogg Ep3_KashOrder66.ogg
ren ep3_kashoutro.ogg Ep3_KashOutro.ogg
ren ep3_outro.ogg Ep3_Outro.ogg
ren ep3_ruinintro.ogg Ep3_RuinIntro.ogg
ren ep3_ruinoutro.ogg Ep3_RuinOutro.ogg
ren ep3_vaderfight1.ogg Ep3_VaderFight1.ogg
ren ep3_vaderfight2.ogg Ep3_VaderFight2.ogg
ren ep3_vaderintro.ogg Ep3_VaderIntro.ogg
ren ep3_vaderoutroextended.ogg Ep3_VaderOutroExtended.ogg
ren ep3_vaderoutroshort.ogg Ep3_VaderOutroShort.ogg
ren ep4_anewhopeintro.ogg Ep4_ANewHopeIntro.ogg
ren ep4_anewhopeoutro.ogg Ep4_ANewHopeOutro.ogg
ren episode4ending.ogg Episode4Ending.ogg
ren episode5ending.ogg Episode5Ending.ogg
ren episode6_ending.ogg Episode6_Ending.ogg
ren hothbattle_intro.ogg HothBattle_Intro.ogg
ren hothbattle_outro.ogg HothBattle_Outro.ogg
ren hothescape_intro.ogg HothEscape_Intro.ogg
ren hothescape_outro.ogg HothEscape_Outro.ogg
ren ij_losttemple_intro.ogg IJ_LostTemple_Intro.ogg
ren ij_losttemple_midtro.ogg IJ_LostTemple_Midtro.ogg
ren ij_losttemple_outrolose.ogg IJ_LostTemple_OutroLose.ogg
ren ij_losttemple_outrowwin.ogg IJ_LostTemple_OutrowWin.ogg
ren jabbaspalace_intro.ogg JabbasPalace_Intro.ogg
ren jabbaspalace_midtro1.ogg JabbasPalace_Midtro1.ogg
ren jabbaspalace_midtro2.ogg JabbasPalace_Midtro2.ogg
ren jabbaspalace_outro.ogg JabbasPalace_Outro.ogg
ren moseisley_intro.ogg MosEisley_Intro.ogg
ren moseisley_midtro.ogg MosEisley_Midtro.ogg
ren moseisley_outro.ogg MosEisley_Outro.ogg
ren sarlaccpit_intro.ogg SarlaccPit_Intro.ogg
ren sarlaccpit_midtro.ogg SarlaccPit_Midtro.ogg
ren sarlaccpit_midtro2.ogg SarlaccPit_Midtro2.ogg
ren sarlaccpit_outro.ogg SarlaccPit_Outro.ogg
ren speederchase_intro.ogg SpeederChase_Intro.ogg
ren speederchase_outro.ogg SpeederChase_Outro.ogg
ren tatooine_intro.ogg Tatooine_Intro.ogg
ren tatooine_outro.ogg Tatooine_Outro.ogg
cd ..\..

:::::: Audio\_Music
cd Audio\_Music
ren act_astchase_abc.ogg Act_AstChase_ABC.ogg
ren act_astchase_cave.ogg Act_AstChase_Cave.ogg
ren act_astchase_d.ogg Act_AstChase_D.ogg
ren act_bonus.ogg Act_Bonus.ogg
ren act_br_tantive.ogg Act_BR_Tantive.ogg
ren act_cc_escape_a.ogg Act_CC_Escape_A.ogg
ren act_cc_escape_bc.ogg Act_CC_Escape_BC.ogg
ren act_cc_trap.ogg Act_CC_Trap.ogg
ren act_dagobah_abce.ogg Act_Dagobah_ABCE.ogg
ren act_dagobah_d.ogg Act_Dagobah_D.ogg
ren act_ds2b_a.ogg Act_DS2B_A.ogg
ren act_ds2b_bc.ogg Act_DS2B_BC.ogg
ren act_ds2b_d.ogg Act_DS2B_D.ogg
ren act_ds2b_efg.ogg Act_DS2B_EFG.ogg
ren act_dsb_appr.ogg Act_DSB_Appr.ogg
ren act_dsb_shieldgone.ogg Act_DSB_ShieldGone.ogg
ren act_dsb_trench.ogg Act_DSB_Trench.ogg
ren act_ds_escape.ogg Act_DS_Escape.ogg
ren act_ds_rescue.ogg Act_DS_Rescue.ogg
ren act_emperorfight.ogg Act_EmperorFight.ogg
ren act_endorbattle_abc.ogg Act_EndorBattle_Abc.ogg
ren act_endorbattle_d.ogg Act_EndorBattle_D.ogg
ren act_gamorrdisco.ogg Act_GamorrDisco.ogg
ren act_hothbattle_acde.ogg Act_HothBattle_ACDE.ogg
ren act_hothbattle_b.ogg Act_HothBattle_B.ogg
ren act_hothescape_abc.ogg Act_HothEscape_Abc.ogg
ren act_hothescape_d.ogg Act_HothEscape_D.ogg
ren act_jabbas_a.ogg Act_Jabbas_A.ogg
ren act_jabbas_bd.ogg Act_Jabbas_Bd.ogg
ren act_jabbas_e.ogg Act_Jabbas_E.ogg
ren act_mosalley.ogg Act_MosAlley.ogg
ren act_moscant.ogg Act_MosCant.ogg
ren act_moshangar.ogg Act_MosHangar.ogg
ren act_mos_a.ogg Act_Mos_A.ogg
ren act_mos_b.ogg Act_Mos_B.ogg
ren act_sarlacc_a.ogg Act_Sarlacc_A.ogg
ren act_sarlacc_b.ogg Act_Sarlacc_B.ogg
ren act_sarlacc_c.ogg Act_Sarlacc_C.ogg
ren act_speederchase.ogg Act_SpeederChase.ogg
ren act_tatooine.ogg Act_Tatooine.ogg
ren act_tatooine_b.ogg Act_Tatooine_B.ogg
ren amb_astchase_cave.ogg Amb_AstChase_Cave.ogg
ren amb_bonus.ogg Amb_Bonus.ogg
ren amb_br_tantive.ogg Amb_BR_Tantive.ogg
ren amb_cc_escape_bc.ogg Amb_CC_Escape_BC.ogg
ren amb_cc_trap.ogg Amb_CC_Trap.ogg
ren amb_dagobah_abce.ogg Amb_Dagobah_ABCE.ogg
ren amb_dagobah_d.ogg Amb_Dagobah_D.ogg
ren amb_dsb.ogg Amb_DSB.ogg
ren amb_dsb_int.ogg Amb_DSB_Int.ogg
ren amb_ds_escape.ogg Amb_DS_Escape.ogg
ren amb_ds_rescue.ogg Amb_DS_Rescue.ogg
ren amb_endorbunker.ogg Amb_EndorBunker.ogg
ren amb_endorforest.ogg Amb_EndorForest.ogg
ren amb_hothbattle_acde.ogg Amb_HothBattle_ACDE.ogg
ren amb_hothbattle_b.ogg Amb_HothBattle_B.ogg
ren amb_hothescape_d.ogg Amb_HothEscape_D.ogg
ren amb_jabbas_bde.ogg Amb_Jabbas_BDE.ogg
ren amb_legocities.ogg Amb_LegoCities.ogg
ren amb_mos.ogg Amb_Mos.ogg
ren amb_mosalley.ogg Amb_Mosalley.ogg
ren amb_moscant.ogg Amb_Moscant.ogg
ren amb_moshangar.ogg Amb_Moshangar.ogg
ren amb_tatooine.ogg Amb_Tatooine.ogg
ren amb_tatooine_b.ogg Amb_Tatooine_B.ogg
ren credits2m.ogg Credits2M.ogg
ren dexinside.ogg DexInside.ogg
ren dexinside_ambience.ogg DexInside_Ambience.ogg
ren dexoutside.ogg DexOutside.ogg
ren dexoutside_ambience.ogg DexOutside_Ambience.ogg
ren ep1_1_action.ogg Ep1_1_Action.ogg
ren ep1_1_ambience.ogg Ep1_1_Ambience.ogg
ren ep1_1_quiet.ogg Ep1_1_Quiet.ogg
ren ep1_2_action.ogg Ep1_2_Action.ogg
ren ep1_2_ambience.ogg Ep1_2_Ambience.ogg
ren ep1_2_quiet.ogg Ep1_2_Quiet.ogg
ren ep1_3_action.ogg Ep1_3_Action.ogg
ren ep1_3_ambience.ogg Ep1_3_Ambience.ogg
ren ep1_3_quiet.ogg Ep1_3_Quiet.ogg
ren ep1_4_action.ogg Ep1_4_Action.ogg
ren ep1_4_ambience.ogg Ep1_4_Ambience.ogg
ren ep1_5_action.ogg Ep1_5_Action.ogg
ren ep1_5_ambience.ogg Ep1_5_Ambience.ogg
ren ep1_5_quiet.ogg Ep1_5_Quiet.ogg
ren ep1_7_action.ogg Ep1_7_Action.ogg
ren ep1_7_ambience.ogg Ep1_7_Ambience.ogg
ren ep1_7_quiet.ogg Ep1_7_Quiet.ogg
ren ep1_anakinsflight_action.ogg Ep1_AnakinsFlight_Action.ogg
ren ep1_anakinsflight_ambience.ogg Ep1_AnakinsFlight_Ambience.ogg
ren ep1_endcredits.ogg Ep1_EndCredits.ogg
ren ep1_textcrawl.ogg Ep1_TextCrawl.ogg
ren ep2_1_actiona_f.ogg Ep2_1_ActionA_F.ogg
ren ep2_1_actionb_e.ogg Ep2_1_ActionB_E.ogg
ren ep2_1_ambiencea_f.ogg Ep2_1_AmbienceA_F.ogg
ren ep2_1_ambienceb_e.ogg Ep2_1_AmbienceB_E.ogg
ren ep2_1_bhp_action.ogg Ep2_1_BHP_Action.ogg
ren ep2_1_bhp_ambience.ogg Ep2_1_BHP_Ambience.ogg
ren ep2_1_quieta_f.ogg Ep2_1_QuietA_F.ogg
ren ep2_1_quietb_e.ogg Ep2_1_QuietB_E.ogg
ren ep2_1_starwarsdisco.ogg Ep2_1_StarWarsDisco.ogg
ren ep2_2_action.ogg Ep2_2_Action.ogg
ren ep2_2_ambience.ogg Ep2_2_Ambience.ogg
ren ep2_2_quiet.ogg Ep2_2_Quiet.ogg
ren ep2_3_action.ogg Ep2_3_Action.ogg
ren ep2_3_ambience.ogg Ep2_3_Ambience.ogg
ren ep2_4_action.ogg Ep2_4_Action.ogg
ren ep2_4_ambience.ogg Ep2_4_Ambience.ogg
ren ep2_5_action.ogg Ep2_5_Action.ogg
ren ep2_5_ambience.ogg Ep2_5_Ambience.ogg
ren ep2_5_quiet.ogg Ep2_5_Quiet.ogg
ren ep2_endcredits.ogg Ep2_EndCredits.ogg
ren ep2_textcrawl.ogg Ep2_TextCrawl.ogg
ren ep3_1_action.ogg Ep3_1_Action.ogg
ren ep3_1_ambience.ogg Ep3_1_Ambience.ogg
ren ep3_2_action.ogg Ep3_2_Action.ogg
ren ep3_2_ambience.ogg Ep3_2_Ambience.ogg
ren ep3_2_quiet.ogg Ep3_2_Quiet.ogg
ren ep3_3_action.ogg Ep3_3_Action.ogg
ren ep3_3_ambience.ogg Ep3_3_Ambience.ogg
ren ep3_4_action.ogg Ep3_4_Action.ogg
ren ep3_4_ambience.ogg Ep3_4_Ambience.ogg
ren ep3_4_quiet.ogg Ep3_4_Quiet.ogg
ren ep3_5_action.ogg Ep3_5_Action.ogg
ren ep3_5_ambience.ogg Ep3_5_Ambience.ogg
ren ep3_5_quiet.ogg Ep3_5_Quiet.ogg
ren ep3_6_action.ogg Ep3_6_Action.ogg
ren ep3_6_ambience.ogg Ep3_6_Ambience.ogg
ren ep3_endcredits.ogg Ep3_EndCredits.ogg
ren ep3_textcrawl.ogg Ep3_TextCrawl.ogg
ren ep4_bonus_action.ogg Ep4_Bonus_Action.ogg
ren ep4_bonus_ambience.ogg Ep4_Bonus_Ambience.ogg
ren ep4_bonus_quiet.ogg Ep4_Bonus_Quiet.ogg
ren ep4_endcredits.ogg Ep4_EndCredits.ogg
ren ep4_textcrawl.ogg Ep4_TextCrawl.ogg
ren ep5_endcredits.ogg Ep5_EndCredits.ogg
ren ep5_textcrawl.ogg Ep5_TextCrawl.ogg
ren ep6_endcredits.ogg Ep6_EndCredits.ogg
ren ep6_textcrawl.ogg Ep6_TextCrawl.ogg
ren ij_act_level1.ogg IJ_Act_Level1.ogg
ren ij_act_level2.ogg IJ_Act_Level2.ogg
ren ij_act_level3.ogg IJ_Act_Level3.ogg
ren ij_amb_level1.ogg IJ_Amb_Level1.ogg
ren ij_amb_placeholder.ogg IJ_Amb_Placeholder.ogg
ren ij_credits.ogg IJ_Credits.ogg
ren ij_gameover.ogg IJ_GameOver.ogg
ren ij_qui_level1.ogg IJ_Qui_Level1.ogg
ren ij_qui_level2.ogg IJ_Qui_Level2.ogg
ren ij_qui_level3.ogg IJ_Qui_Level3.ogg
ren ij_titles.ogg IJ_Titles.ogg
ren qui_bonus.ogg Qui_Bonus.ogg
ren qui_br_tantive.ogg Qui_BR_Tantive.ogg
ren qui_cc_escape_a.ogg Qui_CC_Escape_A.ogg
ren qui_cc_escape_bc.ogg Qui_CC_Escape_BC.ogg
ren qui_cc_trap.ogg Qui_CC_Trap.ogg
ren qui_dagobah_abce.ogg Qui_Dagobah_ABCE.ogg
ren qui_dagobah_d.ogg Qui_Dagobah_D.ogg
ren qui_ds_escape.ogg Qui_DS_Escape.ogg
ren qui_ds_rescue.ogg Qui_DS_Rescue.ogg
ren qui_emperorfight.ogg Qui_EmperorFight.ogg
ren qui_endorbattle_abc.ogg Qui_EndorBattle_ABC.ogg
ren qui_endorbattle_d.ogg Qui_EndorBattle_D.ogg
ren qui_hothescape_abc.ogg Qui_HothEscape_Abc.ogg
ren qui_hothescape_d.ogg Qui_HothEscape_D.ogg
ren qui_jabbas_a.ogg Qui_Jabbas_A.ogg
ren qui_jabbas_bd.ogg Qui_Jabbas_BD.ogg
ren qui_legocities.ogg Qui_LegoCities.ogg
ren qui_mosalley.ogg Qui_MosAlley.ogg
ren qui_moscant1.ogg Qui_MosCant1.ogg
ren qui_moscant2.ogg Qui_MosCant2.ogg
ren qui_moshangar.ogg Qui_MosHangar.ogg
ren qui_mos_a.ogg Qui_Mos_A.ogg
ren qui_mos_b.ogg Qui_Mos_B.ogg
ren qui_sarlacc_b.ogg Qui_Sarlacc_B.ogg
ren qui_speederchase.ogg Qui_SpeederChase.ogg
ren qui_tatooine.ogg Qui_Tatooine.ogg
ren qui_tatooine_b.ogg Qui_Tatooine_B.ogg
ren statusscreen.ogg StatusScreen.ogg
ren titles.ogg Titles.ogg

cd ..\..

:::::: Audio\_SoundFX\*
cd Audio\_SoundFX

cd ..\.. 

:::::: Chars folder
cd Chars

:::: Folders
ren 2_1b 2_1B
ren 4lom 4LOM
ren aat AAT
ren admiralackbar AdmiralAckbar
ren amidala Amidala
ren anakin Anakin
ren anakinspod AnakinsPod
ren anakinsspeeder AnakinsSpeeder
ren anakin_boy Anakin_Boy
ren assassindroid AssassinDroid
ren atat ATAT
ren atst ATST
ren att ATT
ren babyskywalker BabySkywalker
ren bantha Bantha
ren barman Barman
ren basketcannon Basketcannon
ren bat Bat
ren battledroid BattleDroid
ren battledroidcomp BattleDroidComp
ren benkenobi BenKenobi
ren bespinguard BespinGuard
ren bibfortuna BibFortuna
ren biggun BigGun
ren bobafett BobaFett
ren bobafett_boy BobaFett_Boy
ren bodyguard Bodyguard
ren boga Boga
ren bomarrmonk BomarrMonk
ren bombtow BombTow
ren bossnass BossNass
ren buzzdroid BuzzDroid
ren cannon Cannon
ren cantinaband CantinaBand
ren captainpanaka CaptainPanaka
ren captaintarpals CaptainTarpals
ren catapult Catapult
ren chewbacca Chewbacca
ren clone Clone
ren clonearc CloneARC
ren clonewalker CloneWalker
ren cloudcar CloudCar
ren cloudcitycitizen CloudCityCitizen
ren commonanims CommonAnims
ren countdooku CountDooku
ren curtains Curtains
ren darthmaul DarthMaul
ren darthplagueis DarthPlagueis
ren darthsidious DarthSidious
ren darthvader DarthVader
ren destroyer Destroyer
ren dewback Dewback
ren dexter Dexter
ren disguisedclone DisguisedClone
ren dookusspeeder DookusSpeeder
ren dragbomb DragBomb
ren drevazan DrEvazan
ren droidstarfighter DroidStarfighter
ren droidtrifighter DroidTrifighter
ren duvet Duvet
ren dwarfspiderdroid DwarfSpiderDroid
ren ewok Ewok
ren falumpaset Falumpaset
ren firetruck FireTruck
ren flashspeeder FlashSpeeder
ren gamorreanguard GamorreanGuard
ren gasgano Gasgano
ren gasganospod GasganosPod
ren genericjedi GenericJedi
ren geonosian Geonosian
ren geonosianfighter GeonosianFighter
ren gonkdroid GonkDroid
ren grabber Grabber
ren grabbercontrol GrabberControl
ren grabberr2control GrabberR2control
ren greedo Greedo
ren grievous Grievous
ren gungan Gungan
ren gunganball GunganBall
ren gunganbongo GunganBongo
ren gunturret GunTurret
ren hailfiredroid HailfireDroid
ren hanincarbonite HanInCarbonite
ren hansolo HanSolo
ren heavyrepeatingcannon HeavyRepeatingCannon
ren ig88 IG88
ren imperialguard ImperialGuard
ren imperialofficer ImperialOfficer
ren imperialshuttle ImperialShuttle
ren imperialspy ImperialSpy
ren jabba Jabba
ren jangofett JangoFett
ren jarjarbinks JarJarBinks
ren jawa Jawa
ren jedistarfighter JediStarfighter
ren jedistarfighter_ep3 JediStarfighter_EP3
ren jumbohomingdroid JumboHomingDroid
ren kaadu Kaadu
ren kaminoan Kaminoan
ren kaminoandroid KaminoanDroid
ren landocalrissian LandoCalrissian
ren lifeboat Lifeboat
ren lobot Lobot
ren lukeskywalker LukeSkywalker
ren lukeskywalker_jedi LukeSkywalker_Jedi
ren macewindu MaceWindu
ren magnet Magnet
ren mapcar MapCar
ren medic Medic
ren millenniumfalcon MillenniumFalcon
ren minikits Minikits
ren miscpod MiscPod
ren miscpod2 MiscPod2
ren mooncar MoonCar
ren moscannon MosCannon
ren moseisleycitizen MosEisleyCitizen
ren mousedroid MouseDroid
ren mtt MTT
ren naboostarfighter NabooStarfighter
ren naffdroid1 NaffDroid1
ren naffdroid2 NaffDroid2
ren naffdroid3 NaffDroid3
ren naffdroid4 NaffDroid4
ren niennumb NienNumb
ren obiwankenobi ObiWanKenobi
ren padme Padme
ren padmegeo PadmeGeo
ren padmepilot PadmePilot
ren palpatine Palpatine
ren pitdroid PitDroid
ren pkdroid PKDroid
ren pondababa PondaBaba
ren princessleia PrincessLeia
ren probedroid ProbeDroid
ren protocoldroids ProtocolDroids
ren quigonjinn QuiGonJinn
ren r2d2 R2D2
ren raft Raft
ren rancor Rancor
ren rebelscum RebelScum
ren repteer RepTeer
ren republicatte RepublicATTE
ren republicgunship RepublicGunship
ren robot_base Robot_Base
ren royalguard RoyalGuard
ren royalnaboostarship RoyalNabooStarship
ren sansweet Sansweet
ren sarlacc Sarlacc
ren saucer Saucer
ren sebulba Sebulba
ren sebulbaspod SebulbasPod
ren sentrydroid SentryDroid
ren service_car Service_Car
ren skeleton Skeleton
ren skiffguard SkiffGuard
ren skiffshadow SkiffShadow
ren slave1 Slave1
ren slave1_lsw1 Slave1_LSW1
ren snake Snake
ren snowmob SnowMob
ren snowspeeder SnowSpeeder
ren spaceman Spaceman
ren speederbike SpeederBike
ren speeder_dooku Speeder_Dooku
ren speeder_land Speeder_Land
ren stap STAP
ren stap2 STAP2
ren stormtrooper Stormtrooper
ren superbattledroid SuperBattleDroid
ren tauntaun Tauntaun
ren tennumb TenNumb
ren theemperor TheEmperor
ren thermaldetonator ThermalDetonator
ren tiebomber TIEBomber
ren tiefighter TIEFighter
ren tiefighterdarth TIEFighterDarth
ren tieinterceptor TIEInterceptor
ren towncar TownCar
ren tractor Tractor
ren tradefederationlandingship TradeFederationLandingShip
ren trainingremote TrainingRemote
ren troopercannon TrooperCannon
ren tuskenraider TuskenRaider
ren ugnaught Ugnaught
ren vulturedroid VultureDroid
ren wa7 WA7
ren wampa Wampa
ren watto Watto
ren weirdo Weirdo
ren wheelbike WheelBike
ren whip Whip
ren womprat WompRat
ren wookieflyer WookieFlyer
ren worm Worm
ren xwing XWing
ren yoda Yoda
ren ywing Ywing
ren zamdroid ZamDroid
ren zamsspeeder ZamsSpeeder
ren zamwesell ZamWesell

:::: Files
ren 2_1b\2_1b.txt 2_1B.txt
ren 2_1b\2_1b_lr_pc.ghg 2_1B_LR_PC.ghg
ren 2_1b\2_1b_pc.ghg 2_1B_PC.ghg
ren 4lom\4lom.txt 4LOM.txt
ren 4lom\4lom_lr_pc.ghg 4LOM_LR_PC.ghg
ren 4lom\4lom_pc.ghg 4LOM_PC.ghg
ren aat\aat.txt AAT.txt
ren aat\aat_lr_pc.ghg AAT_LR_PC.ghg
ren aat\aat_pc.ghg AAT_PC.ghg
ren aat\att_pc.gsc ATT_PC.gsc
ren admiralackbar\admiralackbar.txt AdmiralAckbar.txt
ren admiralackbar\moncalamari.txt MonCalamari.txt
ren admiralackbar\admiralackbar_lr_pc.ghg AdmiralAckbar_LR_PC.ghg
ren admiralackbar\admiralackbar_pc.ghg AdmiralAckbar_PC.ghg
ren admiralackbar\moncalamari_lr_pc.ghg MonCalamari_LR_PC.ghg
ren admiralackbar\moncalamari_pc.ghg MonCalamari_PC.ghg
ren amidala\amidala.txt Amidala.txt
ren amidala\amidala_lr_pc.ghg Amidala_LR_PC.ghg
ren amidala\amidala_pc.ghg Amidala_PC.ghg
ren anakin\anakin_ghost.txt Anakin_Ghost.txt
ren anakin\anakin_jedi.txt Anakin_Jedi.txt
ren anakin\anakin_jediscarred.txt Anakin_JediScarred.txt
ren anakin\anakin_jedi_scarred.txt Anakin_Jedi_Scarred.txt
ren anakin\anakin_padawan.txt Anakin_Padawan.txt
ren anakin\anakin_vader.txt Anakin_Vader.txt
ren anakin\anakin_ghost_lr_pc.ghg Anakin_Ghost_LR_PC.ghg
ren anakin\anakin_ghost_pc.ghg Anakin_Ghost_PC.ghg
ren anakin\anakin_jedi_lr_pc.ghg Anakin_Jedi_LR_PC.ghg
ren anakin\anakin_jedi_pc.ghg Anakin_Jedi_PC.ghg
ren anakin\anakin_jedi_scarred_lr_pc.ghg Anakin_Jedi_Scarred_LR_PC.ghg
ren anakin\anakin_jedi_scarred_pc.ghg Anakin_Jedi_Scarred_PC.ghg
ren anakin\anakin_padawan_lr_pc.ghg Anakin_Padawan_LR_PC.ghg
ren anakin\anakin_padawan_pc.ghg Anakin_Padawan_PC.ghg
ren anakin\anakin_vader_lr_pc.ghg Anakin_Vader_LR_PC.ghg
ren anakin\anakin_vader_pc.ghg Anakin_Vader_PC.ghg
ren anakinspod\anakinspod.txt AnakinsPod.txt
ren anakinspod\anakinspod_green.txt AnakinsPod_Green.txt
ren anakinspod\newanakinspod.txt NewAnakinsPod.txt
ren anakinspod\newanakinspod_green.txt NewAnakinsPod_Green.txt
ren anakinspod\anakinspod_green_lr_pc.ghg AnakinsPod_Green_LR_PC.ghg
ren anakinspod\anakinspod_green_pc.ghg AnakinsPod_Green_PC.ghg
ren anakinspod\anakinspod_lr_pc.ghg AnakinsPod_LR_PC.ghg
ren anakinspod\anakinspod_pc.ghg AnakinsPod_PC.ghg
ren anakinspod\newanakinspod_green_lr_pc.ghg NewAnakinsPod_Green_LR_PC.ghg
ren anakinspod\newanakinspod_green_pc.ghg NewAnakinsPod_Green_PC.ghg
ren anakinspod\newanakinspod_lr_pc.ghg NewAnakinsPod_LR_PC.ghg
ren anakinspod\newanakinspod_pc.ghg NewAnakinsPod_PC.ghg
ren anakinsspeeder\anakinsspeeder.txt AnakinsSpeeder.txt
ren anakinsspeeder\anakinsspeeder_green.txt AnakinsSpeeder_Green.txt
ren anakinsspeeder\anakinsspeeder_green_lr_pc.ghg AnakinsSpeeder_Green_LR_PC.ghg
ren anakinsspeeder\anakinsspeeder_green_pc.ghg AnakinsSpeeder_Green_PC.ghg
ren anakinsspeeder\anakinsspeeder_lr_pc.ghg AnakinsSpeeder_LR_PC.ghg
ren anakinsspeeder\anakinsspeeder_pc.ghg AnakinsSpeeder_PC.ghg
ren anakin_boy\anakin_boy.txt Anakin_Boy.txt
ren anakin_boy\anakin_boy_lr_pc.ghg Anakin_Boy_LR_PC.ghg
ren anakin_boy\anakin_boy_pc.ghg Anakin_Boy_PC.ghg
ren assassindroid\assassindroid.txt AssassinDroid.txt
ren assassindroid\assassindroid_lr_pc.ghg AssassinDroid_LR_PC.ghg
ren assassindroid\assassindroid_pc.ghg AssassinDroid_PC.ghg
ren atat\atat.txt ATAT.txt
ren atat\atat_lr_pc.ghg ATAT_LR_PC.ghg
ren atat\atat_pc.ghg ATAT_PC.ghg
ren atst\atst.txt ATST.txt
ren atst\atst_lowres.txt ATST_LowRes.txt
ren atst\atst_lowres_lr_pc.ghg ATST_LowRes_LR_PC.ghg
ren atst\atst_lowres_pc.ghg ATST_LowRes_PC.ghg
ren atst\atst_lr_pc.ghg ATST_LR_PC.ghg
ren atst\atst_pc.ghg ATST_PC.ghg
ren att\att.txt ATT.txt
ren att\att_lr_pc.ghg ATT_LR_PC.ghg
ren att\att_pc.ghg ATT_PC.ghg
ren att\att_pc.gsc ATT_PC.gsc
ren babyskywalker\babyleia.txt BabyLeia.txt
ren babyskywalker\babyluke.txt BabyLuke.txt
ren babyskywalker\babyleia_lr_pc.ghg BabyLeia_LR_PC.ghg
ren babyskywalker\babyleia_pc.ghg BabyLeia_PC.ghg
ren babyskywalker\babyluke_lr_pc.ghg BabyLuke_LR_PC.ghg
ren babyskywalker\babyluke_pc.ghg BabyLuke_PC.ghg
ren bantha\bantha.txt Bantha.txt
ren bantha\bantha_lr_pc.ghg Bantha_LR_PC.ghg
ren bantha\bantha_pc.ghg Bantha_PC.ghg
ren barman\barman.txt Barman.txt
ren barman\barman_lr_pc.ghg Barman_LR_PC.ghg
ren barman\barman_pc.ghg Barman_PC.ghg
ren basketcannon\basketcannon.txt BasketBasketCannon.txt
ren basketcannon\basketcannon_lr_pc.ghg BasketBasketCannon_LR_PC.ghg
ren basketcannon\basketcannon_pc.ghg BasketBasketCannon_PC.ghg
ren bat\bat.txt Bat\Bat.txt
ren bat\bat_lr_pc.ghg Bat\Bat_LR_PC.ghg
ren bat\bat_pc.ghg Bat\Bat_PC.ghg
ren battledroid\battledroid.txt BattleDroid.txt
ren battledroid\battledroid_commander.txt BattleDroid_Commander.txt
ren battledroid\battledroid_geonosian.txt BattleDroid_Geonosian.txt
ren battledroid\battledroid_security.txt BattleDroid_Security.txt
ren battledroid\battledroid_commander_lr_pc.ghg BattleDroid_Commander_LR_PC.ghg
ren battledroid\battledroid_commander_pc.ghg BattleDroid_Commander_PC.ghg
ren battledroid\battledroid_geonosian_lr_pc.ghg BattleDroid_Geonosian_LR_PC.ghg
ren battledroid\battledroid_geonosian_pc.ghg BattleDroid_Geonosian_PC.ghg
ren battledroid\battledroid_lr_pc.ghg BattleDroid_LR_PC.ghg
ren battledroid\battledroid_pc.ghg BattleDroid_PC.ghg
ren battledroid\battledroid_pc.gsc BattleDroid_PC.gsc
ren battledroid\battledroid_security_lr_pc.ghg BattleDroid_Security_LR_PC.ghg
ren battledroid\battledroid_security_pc.ghg BattleDroid_Security_PC.ghg
ren battledroidcomp\battledroidcomp.txt BattleDroidComp.txt
ren battledroidcomp\battledroidcomp_lr_pc.ghg BattleDroidComp_LR_PC.ghg
ren battledroidcomp\battledroidcomp_pc.ghg BattleDroidComp_PC.ghg
ren benkenobi\benkenobi.txt BenKenobi.txt
ren benkenobi\ghostbenkenobi.txt GhostBenKenobi.txt
ren benkenobi\benkenobi_lr_pc.ghg BenKenobi_LR_PC.ghg
ren benkenobi\benkenobi_pc.ghg BenKenobi_PC.ghg
ren benkenobi\ghostbenkenobi_lr_pc.ghg GhostBenKenobi_LR_PC.ghg
ren benkenobi\ghostbenkenobi_pc.ghg GhostBenKenobi_PC.ghg
ren bespinguard\bespinguard.txt BespinGuard.txt
ren bespinguard\bespinguard_lr_pc.ghg BespinGuard_LR_PC.ghg
ren bespinguard\bespinguard_pc.ghg BespinGuard_PC.ghg
ren bibfortuna\bibfortuna.txt BibFortuna.txt
ren bibfortuna\bibfortuna_lr_pc.ghg BibFortuna_LR_PC.ghg
ren bibfortuna\bibfortuna_pc.ghg BibFortuna_PC.ghg
ren biggun\biggun.txt BigGun.txt
ren biggun\biggun_lr_pc.ghg BigGun_LR_PC.ghg
ren biggun\biggun_pc.ghg BigGun_PC.ghg
ren bobafett\bobafett.txt BobaFett.txt
ren bobafett\bobafett_lr_pc.ghg BobaFett_LR_PC.ghg
ren bobafett\bobafett_pc.ghg BobaFett_PC.ghg
ren bobafett_boy\bobafett_boy.txt BobaFett_Boy.txt
ren bobafett_boy\bobafett_boy_lr_pc.ghg BobaFett_Boy_LR_PC.ghg
ren bobafett_boy\bobafett_boy_pc.ghg BobaFett_Boy_PC.ghg
ren bodyguard\bodyguard.txt Bodyguard.txt
ren bodyguard\bodyguard_lr_pc.ghg Bodyguard_LR_PC.ghg
ren bodyguard\bodyguard_pc.ghg Bodyguard_PC.ghg
ren boga\boga.txt Boga.txt
ren boga\boga_lr_pc.ghg Boga_LR_PC.ghg
ren boga\boga_pc.ghg Boga_PC.ghg
ren bomarrmonk\bomarrmonk.txt BomarrMonk.txt
ren bomarrmonk\bomarrmonk_lr_pc.ghg BomarrMonk_LR_PC.ghg
ren bomarrmonk\bomarrmonk_pc.ghg BomarrMonk_PC.ghg
ren bombtow\bombtow.txt BombTow.txt
ren bombtow\bombtow_lr_pc.ghg BombTow_LR_PC.ghg
ren bombtow\bombtow_pc.ghg BombTow_PC.ghg
ren bombtow\bombtow_pc.gsc BombTow_PC.gsc
ren bossnass\bossnass.txt BossNass.txt
ren bossnass\bossnass_lr_pc.ghg BossNass_LR_PC.ghg
ren bossnass\bossnass_pc.ghg BossNass_PC.ghg
ren buzzdroid\buzzdroid.txt BuzzDroid.txt
ren buzzdroid\buzzdroid_lr_pc.ghg BuzzDroid_LR_PC.ghg
ren buzzdroid\buzzdroid_pc.ghg BuzzDroid_PC.ghg
ren cannon\cannon.txt Cannon.txt
ren cannon\cannon_lr_pc.ghg Cannon_LR_PC.ghg
ren cannon\cannon_pc.ghg Cannon_PC.ghg
ren cantinaband\cantinaband.txt CantinaBand.txt
ren cantinaband\cantinaband_lr_pc.ghg CantinaBand_LR_PC.ghg
ren cantinaband\cantinaband_pc.ghg CantinaBand_PC.ghg
ren captainpanaka\captainpanaka.txt CaptainPanaka.txt
ren captainpanaka\captainpanaka_lr_pc.ghg CaptainPanaka_LR_PC.ghg
ren captainpanaka\captainpanaka_pc.ghg CaptainPanaka_PC.ghg
ren captaintarpals\captaintarpals.txt CaptainTarpals.txt
ren captaintarpals\gungan.txt Gungan.txt
ren captaintarpals\captaintarpals_lr_pc.ghg CaptainTarpals_LR_PC.ghg
ren captaintarpals\captaintarpals_pc.ghg CaptainTarpals_PC.ghg
ren captaintarpals\gungan_lr_pc.ghg Gungan_LR_PC.ghg
ren captaintarpals\gungan_pc.ghg Gungan_PC.ghg
ren catapult\catapult.txt Catapult.txt
ren catapult\catapult_lr_pc.ghg Catapult_LR_PC.ghg
ren catapult\catapult_pc.ghg Catapult_PC.ghg
ren chewbacca\chewbacca.txt Chewbacca.txt
ren chewbacca\wookie.txt Wookie.txt
ren chewbacca\chewbacca_lr_pc.ghg Chewbacca_LR_PC.ghg
ren chewbacca\chewbacca_pc.ghg Chewbacca_PC.ghg
ren chewbacca\wookie_lr_pc.ghg Wookie_LR_PC.ghg
ren chewbacca\wookie_pc.ghg Wookie_PC.ghg
ren clone\clone.txt Clone.txt
ren clone\clone_ep3.txt Clone_Ep3.txt
ren clone\clone_ep3_pilot.txt Clone_Ep3_Pilot.txt
ren clone\clone_ep3_sand.txt Clone_Ep3_Sand.txt
ren clone\clone_ep3_wwamp.txt Clone_Ep3_Wwamp.txt
ren clone\clone_ep3_walker.txt Clone_Ep3_Walker.txt
ren clone\stormtrooper.txt Stormtrooper.txt
ren clone\clone_ep3_lr_pc.ghg Clone_Ep3_LR_PC.ghg
ren clone\clone_ep3_pc.ghg Clone_Ep3_PC.ghg
ren clone\clone_ep3_pilot_lr_pc.ghg Clone_Ep3_Pilot_LR_PC.ghg
ren clone\clone_ep3_pilot_pc.ghg Clone_Ep3_Pilot_PC.ghg
ren clone\clone_ep3_sand_lr_pc.ghg Clone_Ep3_Sand_LR_PC.ghg
ren clone\clone_ep3_sand_pc.ghg Clone_Ep3_Sand_PC.ghg
ren clone\clone_ep3_swamp_lr_pc.ghg Clone_Ep3_Swamp_LR_PC.ghg
ren clone\clone_ep3_swamp_pc.ghg Clone_Ep3_Swamp_PC.ghg
ren clone\clone_ep3_walker_lr_pc.ghg Clone_Ep3_Walker_LR_PC.ghg
ren clone\clone_ep3_walker_pc.ghg Clone_Ep3_Walker_PC.ghg
ren clone\clone_lr_pc.ghg Clone_LR_PC.ghg
ren clone\clone_pc.ghg Clone_PC.ghg
ren clone\stormtrooper_lr_pc.ghg Stormtrooper_LR_PC.ghg
ren clone\stormtrooper_pc.ghg Stormtrooper_PC.ghg
ren clonearc\clonearc.txt CloneARC.txt
ren clonearc\clonearc_lr_pc.ghg CloneARC_LR_PC.ghg
ren clonearc\clonearc_pc.ghg CloneARC_PC.ghg
ren clonewalker\clonewalker.txt CloneWalker.txt
ren clonewalker\clonewalker_lr_pc.ghg CloneWalker_LR_PC.ghg
ren clonewalker\clonewalker_pc.ghg CloneWalker_PC.ghg
ren cloudcar\cloudcar.txt CloudCar.txt
ren cloudcar\cloudcar_lr_pc.ghg CloudCar_LR_PC.ghg
ren cloudcar\cloudcar_pc.ghg CloudCar_PC.ghg
ren cloudcitycitizen\cantinaaliens.txt CantinaAliens.txt
ren cloudcitycitizen\cloudcitycitizen.txt CloudCityCitizen.txt
ren cloudcitycitizen\cantinaaliens_lr_pc.ghg CantinaAliens_LR_PC.ghg
ren cloudcitycitizen\cantinaaliens_pc.ghg CantinaAliens_PC.ghg
ren cloudcitycitizen\cantinaaliens.hgo_pc.gsc CantinaAliens.hgo_PC.gsc
ren cloudcitycitizen\cloudcitycitizen_lr_pc.ghg CloudCityCitizen_LR_PC.ghg
ren cloudcitycitizen\cloudcitycitizen_pc.ghg CloudCityCitizen_PC.ghg
ren countdooku\countdooku.txt CountDooku.txt
ren countdooku\countdooku_lr_pc.ghg CountDooku_LR_PC.ghg
ren countdooku\countdooku_pc.ghg CountDooku_PC.ghg
ren curtains\curtains.txt Curtains.txt
ren curtains\curtains_lr_pc.ghg Curtains_LR_PC.ghg
ren curtains\curtains_pc.ghg Curtains_PC.ghg
ren darthmaul\darthmaul.txt DarthMaul.txt
ren darthmaul\darthmaul_lr_pc.ghg DarthMaul_LR_PC.ghg
ren darthmaul\darthmaul_pc.ghg DarthMaul_PC.ghg
ren darthplagueis\darthplagueis.txt DarthPlagueis\DarthPlagueis.txt
ren darthsidious\darthsidious.txt DarthSidious.txt
ren darthsidious\darthsidious_lr_pc.ghg DarthSidious_LR_PC.ghg
ren darthsidious\darthsidious_pc.ghg DarthSidious_PC.ghg
ren darthvader\darthvader.txt DarthVader.txt
ren darthvader\darthvader_lr_pc.ghg DarthVader_LR_PC.ghg
ren darthvader\darthvader_pc.ghg DarthVader_PC.ghg
ren destroyer\destroyer.txt Destroyer.txt
ren destroyer\_destroyer.txt _Destroyer.txt
ren destroyer\destroyer_lr_pc.ghg Destroyer_LR_PC.ghg
ren destroyer\destroyer_pc.ghg Destroyer_PC.ghg
ren dewback\dewback.txt Dewback.txt
ren dewback\dewback_lr_pc.ghg Dewback_LR_PC.ghg
ren dewback\dewback_pc.ghg Dewback_PC.ghg
ren dexter\dexter.txt Dexter.txt
ren dexter\dexter_lr_pc.ghg Dexter_LR_PC.ghg
ren dexter\dexter_pc.ghg Dexter_PC.ghg
ren disguisedclone\disguisedclone.txt DisguisedClone.txt
ren disguisedclone\disguisedclone_lr_pc.ghg DisguisedClone_LR_PC.ghg
ren disguisedclone\disguisedclone_pc.ghg DisguisedClone_PC.ghg
ren dookusspeeder\dookusspeeder.txt DookusSpeeder.txt
ren dookusspeeder\dookusspeeder_lr_pc.ghg DookusSpeeder_LR_PC.ghg
ren dookusspeeder\dookusspeeder_pc.ghg DookusSpeeder_PC.ghg
ren dragbomb\dragbomb.txt DragBomb.txt
ren dragbomb\dragbomb_lr_pc.ghg DragBomb_LR_PC.ghg
ren dragbomb\dragbomb_pc.ghg DragBomb_PC.ghg
ren drevazan\drevazan.txt DrEvazan.txt
ren drevazan\drevazan_lr_pc.ghg DrEvazan_LR_PC.ghg
ren drevazan\drevazan_pc.ghg DrEvazan_PC.ghg
ren droidstarfighter\droidstarfighter.txt DroidStarfighter.txt
ren droidstarfighter\droidstarfighter_lr_pc.ghg DroidStarfighter_LR_PC.ghg
ren droidstarfighter\droidstarfighter_pc.ghg DroidStarfighter_PC.ghg
ren droidtrifighter\droidtrifighter.txt DroidTriFighter.txt
ren droidtrifighter\droidtrifighter_lr_pc.ghg DroidTriFighter_LR_PC.ghg
ren droidtrifighter\droidtrifighter_pc.ghg DroidTriFighter_PC.ghg
ren droidtrifighter\droidtrifighter_pc.gsc DroidTriFighter_PC.gsc
ren duvet\duvet.txt Duvet.txt
ren duvet\duvet_lr_pc.ghg Duvet_LR_PC.ghg
ren duvet\duvet_pc.ghg Duvet_PC.ghg
ren dwarfspiderdroid\dwarfspiderdroid.txt DwarfSpiderDroid.txt
ren dwarfspiderdroid\dwarfspiderdroid_lr_pc.ghg DwarfSpiderDroid_LR_PC.ghg
ren dwarfspiderdroid\dwarfspiderdroid_pc.ghg DwarfSpiderDroid_PC.ghg
ren ewok\ewok.txt Ewok.txt
ren ewok\wicket.txt Wicket.txt
ren ewok\ewok_lr_pc.ghg Ewok_LR_PC.ghg
ren ewok\ewok_pc.ghg Ewok_PC.ghg
ren ewok\jump_lr_pc.ghg Jump_LR_PC.ghg
ren ewok\jump_pc.ghg Jump_PC.ghg
ren ewok\wicket_lr_pc.ghg Wicket_LR_PC.ghg
ren ewok\wicket_pc.ghg Wicket_PC.ghg
ren falumpaset\falumpaset.txt Falumpaset.txt
ren falumpaset\falumpaset_lr_pc.ghg Falumpaset_LR_PC.ghg
ren falumpaset\falumpaset_pc.ghg Falumpaset_PC.ghg
ren firetruck\firetruck.txt FireTruck.txt
ren firetruck\firetruck_lr_pc.ghg FireTruck_LR_PC.ghg
ren firetruck\firetruck_pc.ghg FireTruck_PC.ghg
ren flashspeeder\copy_of_flashspeeder.txt Copy_of_FlashSpeeder.txt
ren flashspeeder\flashspeeder.txt FlashSpeeder.txt
ren flashspeeder\flashspeeder_lr_pc.ghg FlashSpeeder_LR_PC.ghg
ren flashspeeder\flashspeeder_pc.ghg FlashSpeeder_PC.ghg
ren gamorreanguard\gamorreanguard.txt GamorreanGuard.txt
ren gamorreanguard\gamorreanguard_lr_pc.ghg GamorreanGuard_LR_PC.ghg
ren gamorreanguard\gamorreanguard_pc.ghg GamorreanGuard_PC.ghg
ren gasgano\gasgano.txt Gasgano.txt
ren gasgano\gasgano_lr_pc.ghg Gasgano_LR_PC.ghg
ren gasgano\gasgano_pc.ghg Gasgano_PC.ghg
ren gasganospod\gasganospod.txt GasganosPod.txt
ren gasganospod\anakinspod_lr_pc.ghg AnakinsPod_LR_PC.ghg
ren gasganospod\anakinspod_pc.ghg AnakinsPod_PC.ghg
ren gasganospod\gasganospod_lr_pc.ghg GasganosPod_LR_PC.ghg
ren gasganospod\gasganospod_pc.ghg GasganosPod_PC.ghg
ren genericjedi\aylasecura.txt AylaSecura.txt
ren genericjedi\bob.txt Bob.txt
ren genericjedi\kiadimundi.txt KiAdiMundi.txt
ren genericjedi\kitfisto.txt KitFisto.txt
ren genericjedi\luminara.txt Luminara.txt
ren genericjedi\plokoon.txt PloKoon.txt
ren genericjedi\shaakti.txt ShaakTi.txt
ren genericjedi\aylasecura_lr_pc.ghg AylaSecura_LR_PC.ghg
ren genericjedi\aylasecura_pc.ghg AylaSecura_PC.ghg
ren genericjedi\bob_lr_pc.ghg Bob_LR_PC.ghg
ren genericjedi\bob_pc.ghg Bob_PC.ghg
ren genericjedi\kiadimundi_lr_pc.ghg KiAdiMundi_LR_PC.ghg
ren genericjedi\kiadimundi_pc.ghg KiAdiMundi_PC.ghg
ren genericjedi\kitfisto_lr_pc.ghg KitFisto_LR_PC.ghg
ren genericjedi\kitfisto_pc.ghg KitFisto_PC.ghg
ren genericjedi\luminara_lr_pc.ghg Luminara_LR_PC.ghg
ren genericjedi\luminara_pc.ghg Luminara_PC.ghg
ren genericjedi\plokoon_lr_pc.ghg PloKoon_LR_PC.ghg
ren genericjedi\plokoon_pc.ghg PloKoon_PC.ghg
ren genericjedi\shaakti_lr_pc.ghg ShaakTi_LR_PC.ghg
ren genericjedi\shaakti_pc.ghg ShaakTi_PC.ghg
ren geonosian\geonosian.txt Geonosian.txt
ren geonosian\geonosian_lr_pc.ghg Geonosian_LR_PC.ghg
ren geonosian\geonosian_pc.ghg Geonosian_PC.ghg
ren geonosianfighter\geonosianfighter.txt GeonosianFighter.txt
ren geonosianfighter\geonosianfighter_lr_pc.ghg GeonosianFighter_LR_PC.ghg
ren geonosianfighter\geonosianfighter_pc.ghg GeonosianFighter_PC.ghg
ren gonkdroid\gonkdroid.txt GonkDroid.txt
ren gonkdroid\gonkdroid_lr_pc.ghg GonkDroid_LR_PC.ghg
ren gonkdroid\gonkdroid_pc.ghg GonkDroid_PC.ghg
ren grabber\grabber.txt Grabber.txt
ren grabber\grabber_lr_pc.ghg Grabber_LR_PC.ghg
ren grabber\grabber_pc.ghg Grabber_PC.ghg
ren grabbercontrol\grabbercontrol.txt GrabberControl.txt
ren grabbercontrol\grabbercontrol_lr_pc.ghg GrabberControl_LR_PC.ghg
ren grabbercontrol\grabbercontrol_pc.ghg GrabberControl_PC.ghg
ren grabberr2control\grabberr2control.txt GrabberR2Control.txt
ren grabberr2control\grabberr2control_lr_pc.ghg GrabberR2Control_LR_PC.ghg
ren grabberr2control\grabberr2control_pc.ghg GrabberR2Control_PC.ghg
ren greedo\bossk.txt Bossk.txt
ren greedo\dengar.txt Dengar.txt
ren greedo\greedo.txt Greedo.txt
ren greedo\bossk_lr_pc.ghg Bossk_LR_PC.ghg
ren greedo\bossk_pc.ghg Bossk_PC.ghg
ren greedo\dengar_lr_pc.ghg Dengar_LR_PC.ghg
ren greedo\dengar_pc.ghg Dengar_PC.ghg
ren greedo\greedo_lr_pc.ghg Greedo_LR_PC.ghg
ren greedo\greedo_pc.ghg Greedo_PC.ghg
ren grievous\grievous.txt Grievous.txt
ren grievous\grievous_lr_pc.ghg Grievous_LR_PC.ghg
ren grievous\grievous_pc.ghg Grievous_PC.ghg
ren gungan\gungan.txt Gungan.txt
ren gungan\gungan_lr_pc.ghg Gungan_LR_PC.ghg
ren gungan\gungan_pc.ghg Gungan_PC.ghg
ren gunganball\gunganball.txt GunganBall.txt
ren gunganball\gunganball_lr_pc.ghg GunganBall_LR_PC.ghg
ren gunganball\gunganball_pc.ghg GunganBall_PC.ghg
ren gunganbongo\gunganbongo.txt GunganBongo.txt
ren gunganbongo\gunganbongo_lr_pc.ghg GunganBongo_LR_PC.ghg
ren gunganbongo\gunganbongo_pc.ghg GunganBongo_PC.ghg
ren gunganbongo\gunganbongo_pc.gsc GunganBongo_PC.gsc
ren gunturret\gunturret_lr_pc.ghg GunTurret_LR_PC.ghg
ren gunturret\gunturret_pc.ghg GunTurret_PC.ghg
ren hailfiredroid\hailfiredroid.txt HailfireDroid.txt
ren hailfiredroid\hailfiredroid_lr_pc.ghg HailfireDroid_LR_PC.ghg
ren hailfiredroid\hailfiredroid_pc.ghg HailfireDroid_PC.ghg
ren hanincarbonite\hanincarbonite.txt HanInCarbonite.txt
ren hanincarbonite\hanincarbonite_lr_pc.ghg HanInCarbonite_LR_PC.ghg
ren hanincarbonite\hanincarbonite_pc.ghg HanInCarbonite_PC.ghg
ren hansolo\hansolo.txt HanSolo.txt
ren hansolo\hansolo_endor.txt HanSolo_Endor.txt
ren hansolo\hansolo_hood.txt HanSolo_Hood.txt
ren hansolo\hansolo_hoth.txt HanSolo_Hoth.txt
ren hansolo\hansolo_indy.txt HanSolo_Indy.txt
ren hansolo\hansolo_skiff.txt HanSolo_Skiff.txt
ren hansolo\hansolo_stormtrooper.txt HanSolo_Stormtrooper.txt
ren hansolo\hansolo_endor_lr_pc.ghg HanSolo_Endor_LR_PC.ghg
ren hansolo\hansolo_endor_pc.ghg HanSolo_Endor_PC.ghg
ren hansolo\hansolo_hood_lr_pc.ghg HanSolo_Hood_LR_PC.ghg
ren hansolo\hansolo_hood_pc.ghg HanSolo_Hood_PC.ghg
ren hansolo\hansolo_hoth_lr_pc.ghg HanSolo_Hoth_LR_PC.ghg
ren hansolo\hansolo_hoth_pc.ghg HanSolo_Hoth_PC.ghg
ren hansolo\hansolo_indy_lr_pc.ghg HanSolo_Indy_LR_PC.ghg
ren hansolo\hansolo_indy_pc.ghg HanSolo_Indy_PC.ghg
ren hansolo\hansolo_lr_pc.ghg HanSolo_LR_PC.ghg
ren hansolo\hansolo_pc.ghg HanSolo_PC.ghg
ren hansolo\hansolo_skiff_lr_pc.ghg HanSolo_Skiff_LR_PC.ghg
ren hansolo\hansolo_skiff_pc.ghg HanSolo_Skiff_PC.ghg
ren hansolo\hansolo_stormtrooper_lr_pc.ghg HanSolo_Stormtrooper_LR_PC.ghg
ren hansolo\hansolo_stormtrooper_pc.ghg HanSolo_Stormtrooper_PC.ghg
ren heavyrepeatingcannon\heavyrepeatingcannon.txt HeavyRepeatingCannon.txt
ren heavyrepeatingcannon\heavyrepeatingcannon_lr_pc.ghg HeavyRepeatingCannon_LR_PC.ghg
ren heavyrepeatingcannon\heavyrepeatingcannon_pc.ghg HeavyRepeatingCannon_PC.ghg
ren ig88\ig88.txt IG88.txt
ren ig88\ig88_lr_pc.ghg IG88_LR_PC.ghg
ren ig88\ig88_pc.ghg IG88_PC.ghg
ren imperialguard\imperialguard.txt ImperialGuard.txt
ren imperialguard\imperialguard_lr_pc.ghg ImperialGuard_LR_PC.ghg
ren imperialguard\imperialguard_pc.ghg ImperialGuard_PC.ghg
ren imperialofficer\generalveers.txt GeneralVeers.txt
ren imperialofficer\grandmofftarkin.txt GrandMoffTarkin.txt
ren imperialofficer\imperialofficer.txt ImperialOfficer.txt
ren imperialofficer\imperialshuttlepilot.txt ImperialShuttlePilot.txt
ren imperialofficer\generalveers_lr_pc.ghg GeneralVeers_LR_PC.ghg
ren imperialofficer\generalveers_pc.ghg GeneralVeers_PC.ghg
ren imperialofficer\generalveers_pc.gsc GeneralVeers_PC.gsc
ren imperialofficer\grandmofftarkin_lr_pc.ghg GrandMoffTarkin_LR_PC.ghg
ren imperialofficer\grandmofftarkin_pc.ghg GrandMoffTarkin_PC.ghg
ren imperialofficer\imperialofficer_lr_pc.ghg ImperialOfficer_LR_PC.ghg
ren imperialofficer\imperialofficer_pc.ghg ImperialOfficer_PC.ghg
ren imperialofficer\imperialshuttlepilot_lr_pc.ghg ImperialShuttlePilot_LR_PC.ghg
ren imperialofficer\imperialshuttlepilot_pc.ghg ImperialShuttlePilot_PC.ghg
ren imperialshuttle\imperialshuttle.txt ImperialShuttle.txt
ren imperialshuttle\imperialshuttle_lr_pc.ghg ImperialShuttle_LR_PC.ghg
ren imperialshuttle\imperialshuttle_pc.ghg ImperialShuttle_PC.ghg
ren imperialspy\imperialspy.txt ImperialSpy.txt
ren imperialspy\imperialspy_lr_pc.ghg ImperialSpy_LR_PC.ghg
ren imperialspy\imperialspy_pc.ghg ImperialSpy_PC.ghg
ren jabba\jabba.txt Jabba.txt
ren jabba\jabba_lr_pc.ghg Jabba_LR_PC.ghg
ren jabba\jabba_pc.ghg Jabba_PC.ghg
ren jangofett\jangofett.txt JangoFett.txt
ren jangofett\jangofett_lr_pc.ghg JangoFett_LR_PC.ghg
ren jangofett\jangofett_pc.ghg JangoFett_PC.ghg
ren jarjarbinks\jarjarbinks.txt JarJarBinks.txt
ren jarjarbinks\jarjarbinks_lr_pc.ghg JarJarBinks_LR_PC.ghg
ren jarjarbinks\jarjarbinks_pc.ghg JarJarBinks_PC.ghg
ren jawa\jawa.txt Jawa.txt
ren jawa\jawa_lr_pc.ghg Jawa_LR_PC.ghg
ren jawa\jawa_pc.ghg Jawa_PC.ghg
ren jedistarfighter\jedistarfighter.txt JediStarfighter.txt
ren jedistarfighter\jedistarfighter_lr_pc.ghg JediStarfighter_LR_PC.ghg
ren jedistarfighter\jedistarfighter_pc.ghg JediStarfighter_PC.ghg
ren jedistarfighter_ep3\jedistarfighter_ep3.txt JediStarfighter_Ep3.txt
ren jedistarfighter_ep3\jedistarfighter_red_ep3.txt JediStarfighter_Red_Ep3.txt
ren jedistarfighter_ep3\jedistarfighter_yellow_ep3.txt JediStarfighter_Yellow_Ep3.txt
ren jedistarfighter_ep3\jedistarfighter_ep3_lr_pc.ghg JediStarfighter_Ep3_LR_PC.ghg
ren jedistarfighter_ep3\jedistarfighter_ep3_pc.ghg JediStarfighter_Ep3_PC.ghg
ren jedistarfighter_ep3\jedistarfighter_red_ep3_lr_pc.ghg JediStarfighter_Red_Ep3_LR_PC.ghg
ren jedistarfighter_ep3\jedistarfighter_red_ep3_pc.ghg JediStarfighter_Red_Ep3_PC.ghg
ren jedistarfighter_ep3\jedistarfighter_yellow_ep3_lr_pc.ghg JediStarfighter_Yellow_Ep3_LR_PC.ghg
ren jedistarfighter_ep3\jedistarfighter_yellow_ep3_pc.ghg JediStarfighter_Yellow_Ep3_PC.ghg
ren jumbohomingdroid\jumbohomingdroid.txt JumboHomingDroid.txt
ren jumbohomingdroid\jumbohomingdroid_lr_pc.ghg JumboHomingDroid_LR_PC.ghg
ren jumbohomingdroid\jumbohomingdroid_pc.ghg JumboHomingDroid_PC.ghg
ren kaadu\kaadu.txt Kaadu.txt
ren kaadu\kaadu_lr_pc.ghg Kaadu_LR_PC.ghg
ren kaadu\kaadu_pc.ghg Kaadu_PC.ghg
ren kaminoan\kamino.txt Kamino.txt
ren kaminoan\lamasu.txt LamaSu.txt
ren kaminoan\taunwe.txt TaunWe.txt
ren kaminoan\kamino_lr_pc.ghg Kamino_LR_PC.ghg
ren kaminoan\kamino_pc.ghg Kamino_PC.ghg
ren kaminoan\lamasu_lr_pc.ghg LamaSu_LR_PC.ghg
ren kaminoan\lamasu_pc.ghg LamaSu_PC.ghg
ren kaminoan\taunwe_lr_pc.ghg TaunWe_LR_PC.ghg
ren kaminoan\taunwe_pc.ghg TaunWe_PC.ghg
ren kaminoandroid\kaminoandroid.txt KaminoanDroid.txt
ren kaminoandroid\kaminoandroid_lr_pc.ghg KaminoanDroid_LR_PC.ghg
ren kaminoandroid\kaminoandroid_pc.ghg KaminoanDroid_PC.ghg
ren landocalrissian\landocalrissian.txt LandoCalrissian.txt
ren landocalrissian\lando_general.txt Lando_General.txt
ren landocalrissian\lando_palaceguard.txt Lando_PalaceGuard.txt
ren landocalrissian\lando_waistcoat.txt Lando_Waistcoat.txt
ren landocalrissian\landocalrissian_lr_pc.ghg LandoCalrissian_LR_PC.ghg
ren landocalrissian\landocalrissian_pc.ghg LandoCalrissian_PC.ghg
ren landocalrissian\lando_general_lr_pc.ghg Lando_General_LR_PC.ghg
ren landocalrissian\lando_general_pc.ghg Lando_General_PC.ghg
ren landocalrissian\lando_palaceguard_lr_pc.ghg Lando_PalaceGuard_LR_PC.ghg
ren landocalrissian\lando_palaceguard_pc.ghg Lando_PalaceGuard_PC.ghg
ren landocalrissian\lando_waistcoat_lr_pc.ghg Lando_Waistcoat_LR_PC.ghg
ren landocalrissian\lando_waistcoat_pc.ghg Lando_Waistcoat_PC.ghg
ren lifeboat\lifeboat.txt LifeBoat.txt
ren lifeboat\lifeboat_lr_pc.ghg LifeBoat_LR_PC.ghg
ren lifeboat\lifeboat_pc.ghg LifeBoat_PC.ghg
ren lobot\lobot.txt Lobot.txt
ren lobot\lobot_lr_pc.ghg Lobot_LR_PC.ghg
ren lobot\lobot_pc.ghg Lobot_PC.ghg
ren lukeskywalker\lukeskywalker_hoth.txt LukeSkywalker_Hoth.txt
ren lukeskywalker\lukeskywalker_pilot.txt LukeSkywalker_Pilot.txt
ren lukeskywalker\lukeskywalker_stormtrooper.txt LukeSkywalker_Stormtrooper.txt
ren lukeskywalker\lukeskywalker_tatooine.txt LukeSkywalker_Tatooine.txt
ren lukeskywalker\lukeskywalker_hoth_lr_pc.ghg LukeSkywalker_Hoth_LR_PC.ghg
ren lukeskywalker\lukeskywalker_hoth_pc.ghg LukeSkywalker_Hoth_PC.ghg
ren lukeskywalker\lukeskywalker_pilot_lr_pc.ghg LukeSkywalker_Pilot_LR_PC.ghg
ren lukeskywalker\lukeskywalker_pilot_pc.ghg LukeSkywalker_Pilot_PC.ghg
ren lukeskywalker\lukeskywalker_stormtrooper_lr_pc.ghg LukeSkywalker_Stormtrooper_LR_PC.ghg
ren lukeskywalker\lukeskywalker_stormtrooper_pc.ghg LukeSkywalker_Stormtrooper_PC.ghg
ren lukeskywalker\lukeskywalker_tatooine_lr_pc.ghg LukeSkywalker_Tatooine_LR_PC.ghg
ren lukeskywalker\lukeskywalker_tatooine_pc.ghg LukeSkywalker_Tatooine_PC.ghg
ren lukeskywalker_jedi\lukeskywalker_bespin.txt LukeSkywalker_Bespin.txt
ren lukeskywalker_jedi\lukeskywalker_ceremony.txt LukeSkywalker_Ceremony.txt
ren lukeskywalker_jedi\lukeskywalker_dagobah.txt LukeSkywalker_Dagobah.txt
ren lukeskywalker_jedi\lukeskywalker_endor.txt LukeSkywalker_Endor.txt
ren lukeskywalker_jedi\lukeskywalker_jedi.txt LukeSkywalker_Jedi.txt
ren lukeskywalker_jedi\lukeskywalker_pyjamas.txt LukeSkywalker_Pyjamas.txt
ren lukeskywalker_jedi\lukeskywalker_bespin_lr_pc.ghg LukeSkywalker_Bespin_LR_PC.ghg
ren lukeskywalker_jedi\lukeskywalker_bespin_pc.ghg LukeSkywalker_Bespin_PC.ghg
ren lukeskywalker_jedi\lukeskywalker_ceremony_lr_pc.ghg LukeSkywalker_Ceremony_LR_PC.ghg
ren lukeskywalker_jedi\lukeskywalker_ceremony_pc.ghg LukeSkywalker_Ceremony_PC.ghg
ren lukeskywalker_jedi\lukeskywalker_dagobah_lr_pc.ghg LukeSkywalker_Dagobah_LR_PC.ghg
ren lukeskywalker_jedi\lukeskywalker_dagobah_pc.ghg LukeSkywalker_Dagobah_PC.ghg
ren lukeskywalker_jedi\lukeskywalker_endor_lr_pc.ghg LukeSkywalker_Endor_LR_PC.ghg
ren lukeskywalker_jedi\lukeskywalker_endor_pc.ghg LukeSkywalker_Endor_PC.ghg
ren lukeskywalker_jedi\lukeskywalker_jedi_lr_pc.ghg LukeSkywalker_Jedi_LR_PC.ghg
ren lukeskywalker_jedi\lukeskywalker_jedi_pc.ghg LukeSkywalker_Jedi_PC.ghg
ren lukeskywalker_jedi\lukeskywalker_pyjamas_lr_pc.ghg LukeSkywalker_Pyjamas_LR_PC.ghg
ren lukeskywalker_jedi\lukeskywalker_pyjamas_pc.ghg LukeSkywalker_Pyjamas_PC.ghg
ren macewindu\macewindu.txt MaceWindu.txt
ren macewindu\macewindu_ep3.txt MaceWindu_Ep3.txt
ren macewindu\lightsabre_lr_pc.ghg Lightsabre_LR_PC.ghg
ren macewindu\lightsabre_pc.ghg Lightsabre_PC.ghg
ren macewindu\macewindu_ep3_lr_pc.ghg MaceWindu_Ep3_LR_PC.ghg
ren macewindu\macewindu_ep3_pc.ghg MaceWindu_Ep3_PC.ghg
ren macewindu\macewindu_lr_pc.ghg MaceWindu_LR_PC.ghg
ren macewindu\macewindu_pc.ghg MaceWindu_PC.ghg
ren magnet\magnet.txt Magnet.txt
ren magnet\magnet_lr_pc.ghg Magnet_LR_PC.ghg
ren magnet\magnet_pc.ghg Magnet_PC.ghg
ren mapcar\mapcar.txt MapCar.txt
ren mapcar\mapcar_lr_pc.ghg MapCar_LR_PC.ghg
ren mapcar\mapcar_pc.ghg MapCar_PC.ghg
ren medic\medic.txt Medic.txt
ren medic\medic_lr_pc.ghg Medic_LR_PC.ghg
ren medic\medic_pc.ghg Medic_PC.ghg
ren millenniumfalcon\millenniumfalcon.txt MillenniumFalcon.txt
ren millenniumfalcon\millenniumfalcon_lr_pc.ghg MillenniumFalcon_LR_PC.ghg
ren millenniumfalcon\millenniumfalcon_pc.ghg MillenniumFalcon_PC.ghg
ren millenniumfalcon\millenniumfalcon_pc.gsc MillenniumFalcon_PC.gsc
ren minikits\mini_atat\mini_atat.txt Mini_ATAT.txt
ren minikits\mini_atat\mini_atat_lr_pc.ghg Mini_ATAT_LR_PC.ghg
ren minikits\mini_atat\mini_atat_pc.ghg Mini_ATAT_PC.ghg
ren minikits\mini_atat\mini_atat_pc.gsc Mini_ATAT_PC.gsc
ren minikits\mini_atst\mini_atst.txt Mini_ATST.txt
ren minikits\mini_atst\mini_atst_lr_pc.ghg Mini_ATST_LR_PC.ghg
ren minikits\mini_atst\mini_atst_pc.ghg Mini_ATST_PC.ghg
ren minikits\mini_atst\mini_atst_pc.gsc Mini_ATST_PC.gsc
ren minikits\mini_atte\mini_atte.txt Mini_ATTE.txt
ren minikits\mini_atte\mini_atte_lr_pc.ghg Mini_ATTE_LR_PC.ghg
ren minikits\mini_atte\mini_atte_pc.ghg Mini_ATTE_PC.ghg
ren minikits\mini_atte\mini_atte_pc.gsc Mini_ATTE_PC.gsc
ren minikits\mini_cloud_car\mini_cloud_car.txt Mini_Cloud_Car.txt
ren minikits\mini_cloud_car\mini_cloud_car_lr_pc.ghg Mini_Cloud_Car_LR_PC.ghg
ren minikits\mini_cloud_car\mini_cloud_car_pc.ghg Mini_Cloud_Car_PC.ghg
ren minikits\mini_cloud_car\mini_cloud_car_pc.gsc Mini_Cloud_Car_PC.gsc
ren minikits\mini_desert_skiff\mini_desert_skiff.txt Mini_Desert_Skiff.txt
ren minikits\mini_desert_skiff\mini_desert_skiff_lr_pc.ghg Mini_Desert_Skiff_LR_PC.ghg
ren minikits\mini_desert_skiff\mini_desert_skiff_pc.ghg Mini_Desert_Skiff_PC.ghg
ren minikits\mini_desert_skiff\mini_desert_skiff_pc.gsc Mini_Desert_Skiff_PC.gsc
ren minikits\mini_droideka\mini_droideka.txt Mini_Droideka.txt
ren minikits\mini_droideka\mini_droideka_lr_pc.ghg Mini_Droideka_LR_PC.ghg
ren minikits\mini_droideka\mini_droideka_pc.ghg Mini_Droideka_PC.ghg
ren minikits\mini_droideka\mini_droideka_pc.gsc Mini_Droideka_PC.gsc
ren minikits\mini_dropship\mini_dropship.txt Mini_Dropship.txt
ren minikits\mini_dropship\mini_dropship_lr_pc.ghg Mini_Dropship_LR_PC.ghg
ren minikits\mini_dropship\mini_dropship_pc.ghg Mini_Dropship_PC.ghg
ren minikits\mini_dropship\mini_dropship_pc.gsc Mini_Dropship_PC.gsc
ren minikits\mini_e3_jedi_starfighter\mini_e3_jedi_starfighter.txt Mini_E3_Jedi_Starfighter.txt
ren minikits\mini_e3_jedi_starfighter\mini_e3_jedi_starfighter_lr_pc.ghg Mini_E3_Jedi_Starfighter_LR_PC.ghg
ren minikits\mini_e3_jedi_starfighter\mini_e3_jedi_starfighter_pc.ghg Mini_E3_Jedi_Starfighter_PC.ghg
ren minikits\mini_e3_jedi_starfighter\mini_e3_jedi_starfighter_pc.gsc Mini_E3_Jedi_Starfighter_PC.gsc
ren minikits\mini_e3_x_wing\mini_e3_x_wing.txt Mini_E3_X_Wing.txt
ren minikits\mini_e3_x_wing\mini_e3_x_wing_lr_pc.ghg Mini_E3_X_Wing_LR_PC.ghg
ren minikits\mini_e3_x_wing\mini_e3_x_wing_pc.ghg Mini_E3_X_Wing_PC.ghg
ren minikits\mini_e3_x_wing\mini_e3_x_wing_pc.gsc Mini_E3_X_Wing_PC.gsc
ren minikits\mini_emergency_ship\mini_emergency_ship.txt Mini_Emergency_Ship.txt
ren minikits\mini_emergency_ship\mini_emergency_ship_lr_pc.ghg Mini_Emergency_Ship_LR_PC.ghg
ren minikits\mini_emergency_ship\mini_emergency_ship_pc.ghg Mini_Emergency_Ship_PC.ghg
ren minikits\mini_emergency_ship\mini_emergency_ship_pc.gsc Mini_Emergency_Ship_PC.gsc
ren minikits\mini_gungan_bongo\mini_gungan_bongo.txt Mini_Gungan_Bongo.txt
ren minikits\mini_gungan_bongo\mini_gungan_bongo_lr_pc.ghg Mini_Gungan_Bongo_LR_PC.ghg
ren minikits\mini_gungan_bongo\mini_gungan_bongo_pc.ghg Mini_Gungan_Bongo_PC.ghg
ren minikits\mini_gungan_bongo\mini_gungan_bongo_pc.gsc Mini_Gungan_Bongo_PC.gsc
ren minikits\mini_gunship\mini_gunship.txt Mini_Gunship.txt
ren minikits\mini_gunship\mini_gunship_lr_pc.ghg Mini_Gunship_LR_PC.ghg
ren minikits\mini_gunship\mini_gunship_pc.ghg Mini_Gunship_PC.ghg
ren minikits\mini_gunship\mini_gunship_pc.gsc Mini_Gunship_PC.gsc
ren minikits\mini_imperial_shuttle\mini_imperial_shuttle.txt Mini_Imperial_Shuttle.txt
ren minikits\mini_imperial_shuttle\mini_imperial_shuttle_lr_pc.ghg Mini_Imperial_Shuttle_LR_PC.ghg
ren minikits\mini_imperial_shuttle\mini_imperial_shuttle_pc.ghg Mini_Imperial_Shuttle_PC.ghg
ren minikits\mini_imperial_shuttle\mini_imperial_shuttle_pc.gsc Mini_Imperial_Shuttle_PC.gsc
ren minikits\mini_jedi_starfighter\mini_jedi_starfighter.txt Mini_Jedi_Starfighter.txt
ren minikits\mini_jedi_starfighter\mini_jedi_starfighter_lr_pc.ghg Mini_Jedi_Starfighter_LR_PC.ghg
ren minikits\mini_jedi_starfighter\mini_jedi_starfighter_pc.ghg Mini_Jedi_Starfighter_PC.ghg
ren minikits\mini_jedi_starfighter\mini_jedi_starfighter.nu_pc.gsc Mini_Jedi_Starfighter.nu_PC.gsc
ren minikits\mini_jedi_starfighter\mini_jedi_starfighter_pc.gsc Mini_Jedi_Starfighter_PC.gsc
ren minikits\mini_land_speeder\mini_land_speeder.txt Mini_Land_Speeder.txt
ren minikits\mini_land_speeder\mini_land_speeder_lr_pc.ghg Mini_Land_Speeder_LR_PC.ghg
ren minikits\mini_land_speeder\mini_land_speeder_pc.ghg Mini_Land_Speeder_PC.ghg
ren minikits\mini_land_speeder\mini_land_speeder_pc.gsc Mini_Land_Speeder_PC.gsc
ren minikits\mini_millennium_falcon\mini_millennium_falcon.txt Mini_Millennium_Falcon.txt
ren minikits\mini_millennium_falcon\mini_millennium_falcon_lr_pc.ghg Mini_Millennium_Falcon_LR_PC.ghg
ren minikits\mini_millennium_falcon\mini_millennium_falcon_pc.ghg Mini_Millennium_Falcon_PC.ghg
ren minikits\mini_millennium_falcon\mini_millennium_falcon_pc.gsc Mini_Millennium_Falcon_PC.gsc
ren minikits\mini_naboo_starfighter\mini_naboo_starfighter.txt Mini_Naboo_Starfighter.txt
ren minikits\mini_naboo_starfighter\mini_naboo_starfighter_lr_pc.ghg Mini_Naboo_Starfighter_LR_PC.ghg
ren minikits\mini_naboo_starfighter\mini_naboo_starfighter_pc.ghg Mini_Naboo_Starfighter_PC.ghg
ren minikits\mini_naboo_starfighter\mini_naboo_starfighter_pc.gsc Mini_Naboo_Starfighter_PC.gsc
ren minikits\mini_republic_cruiser\mini_republic_cruiser.txt Mini_Republic_Cruiser.txt
ren minikits\mini_republic_cruiser\mini_republic_cruiser_lr_pc.ghg Mini_Republic_Cruiser_LR_PC.ghg
ren minikits\mini_republic_cruiser\mini_republic_cruiser_pc.ghg Mini_Republic_Cruiser_PC.ghg
ren minikits\mini_republic_cruiser\mini_republic_cruiser_pc.gsc Mini_Republic_Cruiser_PC.gsc
ren minikits\mini_royal_starship\mini_royal_starship.txt Mini_Royal_Starship.txt
ren minikits\mini_royal_starship\mini_royal_starship_lr_pc.ghg Mini_Royal_Starship_LR_PC.ghg
ren minikits\mini_royal_starship\mini_royal_starship_pc.ghg Mini_Royal_Starship_PC.ghg
ren minikits\mini_royal_starship\mini_royal_starship_pc.gsc Mini_Royal_Starship_PC.gsc
ren minikits\mini_sail_barge\mini_sail_barge.txt Mini_Sail_Barge.txt
ren minikits\mini_sail_barge\mini_sail_barge_lr_pc.ghg Mini_Sail_Barge_LR_PC.ghg
ren minikits\mini_sail_barge\mini_sail_barge_pc.ghg Mini_Sail_Barge_PC.ghg
ren minikits\mini_sail_barge\mini_sail_barge_pc.gsc Mini_Sail_Barge_PC.gsc
ren minikits\mini_sand_crawler\mini_sand_crawler.txt Mini_Sand_Crawler.txt
ren minikits\mini_sand_crawler\mini_sand_crawler_lr_pc.ghg Mini_Sand_Crawler_LR_PC.ghg
ren minikits\mini_sand_crawler\mini_sand_crawler_pc.ghg Mini_Sand_Crawler_PC.ghg
ren minikits\mini_sand_crawler\mini_sand_crawler_pc.gsc Mini_Sand_Crawler_PC.gsc
ren minikits\mini_sebulba_pod\mini_sebulba_pod.txt Mini_Sebulba_Pod.txt
ren minikits\mini_sebulba_pod\mini_sebulba_pod_lr_pc.ghg Mini_Sebulba_Pod_LR_PC.ghg
ren minikits\mini_sebulba_pod\mini_sebulba_pod_pc.ghg Mini_Sebulba_Pod_PC.ghg
ren minikits\mini_sebulba_pod\mini_sebulba_pod_pc.gsc Mini_Sebulba_Pod_PC.gsc
ren minikits\mini_sith_infiltrator\mini_sith_infiltrator.txt Mini_Sith_Infiltrator.txt
ren minikits\mini_sith_infiltrator\mini_sith_infiltrator_lr_pc.ghg Mini_Sith_Infiltrator_LR_PC.ghg
ren minikits\mini_sith_infiltrator\mini_sith_infiltrator_pc.ghg Mini_Sith_Infiltrator_PC.ghg
ren minikits\mini_sith_infiltrator\mini_sith_infiltrator_pc.gsc Mini_Sith_Infiltrator_PC.gsc
ren minikits\mini_slave1\mini_slave1.txt Mini_Mini_Slave1.txt
ren minikits\mini_slave1\mini_slave1_lr_pc.ghg Mini_Mini_Slave1_LR_PC.ghg
ren minikits\mini_slave1\mini_slave1_pc.ghg Mini_Mini_Slave1_PC.ghg
ren minikits\mini_slave1\mini_slave1_pc.gsc Mini_Mini_Slave1_PC.gsc
ren minikits\mini_snow_speeder\mini_snow_speeder.txt Mini_Snow_Speeder.txt
ren minikits\mini_snow_speeder\mini_snow_speeder_lr_pc.ghg Mini_Snow_Speeder_LR_PC.ghg
ren minikits\mini_snow_speeder\mini_snow_speeder_pc.ghg Mini_Snow_Speeder_PC.ghg
ren minikits\mini_snow_speeder\mini_snow_speeder_pc.gsc Mini_Snow_Speeder_PC.gsc
ren minikits\mini_solar_sailor\mini_solar_sailor.txt Mini_Solar_Sailor.txt
ren minikits\mini_solar_sailor\mini_solar_sailor_lr_pc.ghg Mini_Solar_Sailor_LR_PC.ghg
ren minikits\mini_solar_sailor\mini_solar_sailor_pc.ghg Mini_Solar_Sailor_PC.ghg
ren minikits\mini_solar_sailor\mini_solar_sailor_pc.gsc Mini_Solar_Sailor_PC.gsc
ren minikits\mini_star_destroyer\mini_star_destroyer.txt Mini_Star_Destroyer.txt
ren minikits\mini_star_destroyer\mini_star_destroyer_lr_pc.ghg Mini_Star_Destroyer_LR_PC.ghg
ren minikits\mini_star_destroyer\mini_star_destroyer_pc.ghg Mini_Star_Destroyer_PC.ghg
ren minikits\mini_star_destroyer\mini_star_destroyer_pc.gsc Mini_Star_Destroyer_PC.gsc
ren minikits\mini_tie_advanced\mini_tie_advanced.txt Mini_TIE_Advanced.txt
ren minikits\mini_tie_advanced\mini_tie_advanced_lr_pc.ghg Mini_TIE_Advanced_LR_PC.ghg
ren minikits\mini_tie_advanced\mini_tie_advanced_pc.ghg Mini_TIE_Advanced_PC.ghg
ren minikits\mini_tie_advanced\mini_tie_advanced_pc.gsc Mini_TIE_Advanced_PC.gsc
ren minikits\mini_tie_bomber\mini_tie_bomber.txt Mini_TIE_Bomber.txt
ren minikits\mini_tie_bomber\mini_tie_bomber_lr_pc.ghg Mini_TIE_Bomber_LR_PC.ghg
ren minikits\mini_tie_bomber\mini_tie_bomber_pc.ghg Mini_TIE_Bomber_PC.ghg
ren minikits\mini_tie_bomber\mini_tie_bomber_pc.gsc Mini_TIE_Bomber_PC.gsc
ren minikits\mini_tie_fighter\mini_tie_fighter.txt Mini_TIE_Fighter.txt
ren minikits\mini_tie_fighter\mini_tie_fighter_lr_pc.ghg Mini_TIE_Fighter_LR_PC.ghg
ren minikits\mini_tie_fighter\mini_tie_fighter_pc.ghg Mini_TIE_Fighter_PC.ghg
ren minikits\mini_tie_fighter\mini_tie_fighter_pc.gsc Mini_TIE_Fighter_PC.gsc
ren minikits\mini_tie_interceptor\mini_tie_interceptor.txt Mini_TIE_Interceptor.txt
ren minikits\mini_tie_interceptor\mini_tie_interceptor_lr_pc.ghg Mini_TIE_Interceptor_LR_PC.ghg
ren minikits\mini_tie_interceptor\mini_tie_interceptor_pc.ghg Mini_TIE_Interceptor_PC.ghg
ren minikits\mini_tie_interceptor\mini_tie_interceptor_pc.gsc Mini_TIE_Interceptor_PC.gsc
ren minikits\mini_v_wing\mini_v_wing.txt Mini_V_Wing.txt
ren minikits\mini_v_wing\mini_v_wing_lr_pc.ghg Mini_V_Wing_LR_PC.ghg
ren minikits\mini_v_wing\mini_v_wing_pc.ghg Mini_V_Wing_PC.ghg
ren minikits\mini_v_wing\mini_v_wing_pc.gsc Mini_V_Wing_PC.gsc
ren minikits\mini_wookie_cat\mini_wookie_cat.txt Mini_Wookie_Cat.txt
ren minikits\mini_wookie_cat\mini_wookie_cat_lr_pc.ghg Mini_Wookie_Cat_LR_PC.ghg
ren minikits\mini_wookie_cat\mini_wookie_cat_pc.ghg Mini_Wookie_Cat_PC.ghg
ren minikits\mini_wookie_cat\mini_wookie_cat_pc.gsc Mini_Wookie_Cat_PC.gsc
ren minikits\mini_x_wing\mini_x_wing.txt Mini_X_Wing.txt
ren minikits\mini_x_wing\mini_x_wing_lr_pc.ghg Mini_X_Wing_LR_PC.ghg
ren minikits\mini_x_wing\mini_x_wing_pc.ghg Mini_X_Wing_PC.ghg
ren minikits\mini_x_wing\mini_x_wing_pc.gsc Mini_X_Wing_PC.gsc
ren minikits\mini_y_wing\mini_y_wing.txt Mini_Y_Wing.txt
ren minikits\mini_y_wing\mini_y_wing_lr_pc.ghg Mini_Y_Wing_LR_PC.ghg
ren minikits\mini_y_wing\mini_y_wing_pc.ghg Mini_Y_Wing_PC.ghg
ren minikits\mini_y_wing\mini_y_wing_pc.gsc Mini_Y_Wing_PC.gsc
ren minikits\mini_zam_speeder\mini_zam_speeder.txt Mini_Zam_Speeder.txt
ren minikits\mini_zam_speeder\mini_zam_speeder_lr_pc.ghg Mini_Zam_Speeder_LR_PC.ghg
ren minikits\mini_zam_speeder\mini_zam_speeder_pc.ghg Mini_Zam_Speeder_PC.ghg
ren minikits\mini_zam_speeder\mini_zam_speeder_pc.gsc Mini_Zam_Speeder_PC.gsc
ren miscpod\anothermiscpod.txt AnotherMiscPod.txt
ren miscpod\miscpod.txt MiscPod.txt
ren miscpod\anothermiscpod_lr_pc.ghg AnotherMiscPod_LR_PC.ghg
ren miscpod\anothermiscpod_pc.ghg AnotherMiscPod_PC.ghg
ren miscpod\miscpod_lr_pc.ghg MiscPod_LR_PC.ghg
ren miscpod\miscpod_pc.ghg MiscPod_PC.ghg
ren miscpod2\anothermiscpod2.txt AnotherMiscPod2.txt
ren miscpod2\miscpod2.txt MiscPod2.txt
ren miscpod2\anothermiscpod2_lr_pc.ghg AnotherMiscPod2_LR_PC.ghg
ren miscpod2\anothermiscpod2_pc.ghg AnotherMiscPod2_PC.ghg
ren miscpod2\miscpod2_lr_pc.ghg MiscPod2_LR_PC.ghg
ren miscpod2\miscpod2_pc.ghg MiscPod2_PC.ghg
ren mooncar\mooncar.txt MoonCar.txt
ren mooncar\mooncar_lr_pc.ghg MoonCar_LR_PC.ghg
ren mooncar\mooncar_pc.ghg MoonCar_PC.ghg
ren moscannon\moscannon.txt MosCannon.txt
ren moscannon\moscannon_lr_pc.ghg MosCannon_LR_PC.ghg
ren moscannon\moscannon_pc.ghg MosCannon_PC.ghg
ren moseisleycitizen\cantinaaliens.txt CantinaAliens.txt
ren moseisleycitizen\moseisleycitizen.txt MosEisleyCitizen.txt
ren moseisleycitizen\cantinaaliens_lr_pc.ghg CantinaAliens_LR_PC.ghg
ren moseisleycitizen\cantinaaliens_pc.ghg CantinaAliens_PC.ghg
ren moseisleycitizen\moseisleycitizen_lr_pc.ghg MosEisleyCitizen_LR_PC.ghg
ren moseisleycitizen\moseisleycitizen_pc.ghg MosEisleyCitizen_PC.ghg
ren mousedroid\mousedroid.txt MouseDroid.txt
ren mousedroid\mousedroid_lr_pc.ghg MouseDroid_LR_PC.ghg
ren mousedroid\mousedroid_pc.ghg MouseDroid_PC.ghg
ren mtt\mtt.txt MTT.txt
ren mtt\mtt_lr_pc.ghg MTT_LR_PC.ghg
ren mtt\mtt_pc.ghg MTT_PC.ghg
ren mtt\mtt_pc.gsc MTT_PC.gsc
ren naboostarfighter\naboostarfighter.txt NabooStarfighter.txt
ren naboostarfighter\naboostarfighter_blue.txt NabooStarfighter_Blue.txt
ren naboostarfighter\naboostarfighter_lime.txt NabooStarfighter_Lime.txt
ren naboostarfighter\naboostarfighter_blue_lr_pc.ghg NabooStarfighter_Blue_LR_PC.ghg
ren naboostarfighter\naboostarfighter_blue_pc.ghg NabooStarfighter_Blue_PC.ghg
ren naboostarfighter\naboostarfighter_lime_lr_pc.ghg NabooStarfighter_Lime_LR_PC.ghg
ren naboostarfighter\naboostarfighter_lime_pc.ghg NabooStarfighter_Lime_PC.ghg
ren naboostarfighter\naboostarfighter_lr_pc.ghg NabooStarfighter_LR_PC.ghg
ren naboostarfighter\naboostarfighter_pc.ghg NabooStarfighter_PC.ghg
ren naffdroid1\naffdroid1.txt NaffDroid1.txt
ren naffdroid1\naffdroid1_lr_pc.ghg NaffDroid1_LR_PC.ghg
ren naffdroid1\naffdroid1_pc.ghg NaffDroid1_PC.ghg
ren naffdroid2\naffdroid2.txt NaffDroid2.txt
ren naffdroid2\naffdroid2_lr_pc.ghg NaffDroid2_LR_PC.ghg
ren naffdroid2\naffdroid2_pc.ghg NaffDroid2_PC.ghg
ren naffdroid3\naffdroid3.txt NaffDroid3.txt
ren naffdroid3\naffdroid3_lr_pc.ghg NaffDroid3_LR_PC.ghg
ren naffdroid3\naffdroid3_pc.ghg NaffDroid3_PC.ghg
ren naffdroid4\naffdroid4.txt NaffDroid4.txt
ren naffdroid4\naffdroid4_lr_pc.ghg NaffDroid4_LR_PC.ghg
ren naffdroid4\naffdroid4_pc.ghg NaffDroid4_PC.ghg
ren niennumb\niennumb.txt NienNumb.txt
ren niennumb\niennumb_lr_pc.ghg NienNumb_LR_PC.ghg
ren niennumb\niennumb_pc.ghg NienNumb_PC.ghg
ren obiwankenobi\obiwankenobi.txt ObiWanKenobi.txt
ren obiwankenobi\obiwankenobi_ep3.txt ObiWanKenobi_Ep3.txt
ren obiwankenobi\obiwankenobi_jedimaster.txt ObiWanKenobi_JediMaster.txt
ren obiwankenobi\obiwankenobi_ep3_lr_pc.ghg ObiWanKenobi_Ep3_LR_PC.ghg
ren obiwankenobi\obiwankenobi_ep3_pc.ghg ObiWanKenobi_Ep3_PC.ghg
ren obiwankenobi\obiwankenobi_jedimaster_lr_pc.ghg ObiWanKenobi_JediMaster_LR_PC.ghg
ren obiwankenobi\obiwankenobi_jedimaster_pc.ghg ObiWanKenobi_JediMaster_PC.ghg
ren obiwankenobi\obiwankenobi_lr_pc.ghg ObiWanKenobi_LR_PC.ghg
ren obiwankenobi\obiwankenobi_pc.ghg ObiWanKenobi_PC.ghg
ren obiwankenobi\obiwankenobi__lr_pc.ghg ObiWanKenobi__LR_PC.ghg
ren obiwankenobi\obiwankenobi__pc.ghg ObiWanKenobi__PC.ghg
ren padme\padme.txt Padme.txt
ren padme\padmebattle.txt PadmeBattle.txt
ren padme\padmeclawed.txt PadmeClawed.txt
ren padme\padmeuptheduff.txt PadmeUpTheDuff.txt
ren padme\padmeuptheduff_mustafar.txt PadmeUpTheDuff_Mustafar.txt
ren padme\princessleia.txt PrincessLeia.txt
ren padme\padmebattle_lr_pc.ghg PadmeBattle_LR_PC.ghg
ren padme\padmebattle_pc.ghg PadmeBattle_PC.ghg
ren padme\padmeclawed_lr_pc.ghg PadmeClawed_LR_PC.ghg
ren padme\padmeclawed_pc.ghg PadmeClawed_PC.ghg
ren padme\padmeuptheduff_lr_pc.ghg PadmeUpTheDuff_LR_PC.ghg
ren padme\padmeuptheduff_mustafar_lr_pc.ghg PadmeUpTheDuff_Mustafar_LR_PC.ghg
ren padme\padmeuptheduff_mustafar_pc.ghg PadmeUpTheDuff_Mustafar_PC.ghg
ren padme\padmeuptheduff_pc.ghg PadmeUpTheDuff_PC.ghg
ren padme\padme_lr_pc.ghg Padme_LR_PC.ghg
ren padme\padme_pc.ghg Padme_PC.ghg
ren padme\princessleia_lr_pc.ghg PrincessLeia_LR_PC.ghg
ren padme\princessleia_pc.ghg PrincessLeia_PC.ghg
ren padmegeo\padmegeo.txt PadmeGeo.txt
ren padmegeo\padmegeo_lr_pc.ghg PadmeGeo_LR_PC.ghg
ren padmegeo\padmegeo_pc.ghg PadmeGeo_PC.ghg
ren padmepilot\padmepilot.txt PadmePilot.txt
ren padmepilot\padmepilot_lr_pc.ghg PadmePilot_LR_PC.ghg
ren padmepilot\padmepilot_pc.ghg PadmePilot_PC.ghg
ren palpatine\palpatine.txt Palpatine.txt
ren palpatine\palpatine_lr_pc.ghg Palpatine_LR_PC.ghg
ren palpatine\palpatine_pc.ghg Palpatine_PC.ghg
ren pitdroid\pitdroid.txt PitDroid.txt
ren pitdroid\pitdroid_lr_pc.ghg PitDroid_LR_PC.ghg
ren pitdroid\pitdroid_pc.ghg PitDroid_PC.ghg
ren pkdroid\pkdroid.txt PKDroid.txt
ren pkdroid\pkdroid_lr_pc.ghg PKDroid_LR_PC.ghg
ren pkdroid\pkdroid_pc.ghg PKDroid_PC.ghg
ren pondababa\pondababa.txt PondaBaba.txt
ren pondababa\pondababa_lr_pc.ghg PondaBaba_LR_PC.ghg
ren pondababa\pondababa_pc.ghg PondaBaba_PC.ghg
ren princessleia\princessleia.txt PrincessLeia.txt
ren princessleia\princessleia_bespin.txt PrincessLeia_Bespin.txt
ren princessleia\princessleia_boushh.txt PrincessLeia_Boushh.txt
ren princessleia\princessleia_endor.txt PrincessLeia_Endor.txt
ren princessleia\princessleia_hoth.txt PrincessLeia_Hoth.txt
ren princessleia\princessleia_prisoner.txt PrincessLeia_Prisoner.txt
ren princessleia\princessleia_slave.txt PrincessLeia_Slave.txt
ren princessleia\princessleia_bespin_lr_pc.ghg PrincessLeia_Bespin_LR_PC.ghg
ren princessleia\princessleia_bespin_pc.ghg PrincessLeia_Bespin_PC.ghg
ren princessleia\princessleia_boushh_lr_pc.ghg PrincessLeia_Boushh_LR_PC.ghg
ren princessleia\princessleia_boushh_pc.ghg PrincessLeia_Boushh_PC.ghg
ren princessleia\princessleia_endor_lr_pc.ghg PrincessLeia_Endor_LR_PC.ghg
ren princessleia\princessleia_endor_pc.ghg PrincessLeia_Endor_PC.ghg
ren princessleia\princessleia_hoth_lr_pc.ghg PrincessLeia_Hoth_LR_PC.ghg
ren princessleia\princessleia_hoth_pc.ghg PrincessLeia_Hoth_PC.ghg
ren princessleia\princessleia_lr_pc.ghg PrincessLeia_LR_PC.ghg
ren princessleia\princessleia_pc.ghg PrincessLeia_PC.ghg
ren princessleia\princessleia_prisoner_lr_pc.ghg PrincessLeia_Prisoner_LR_PC.ghg
ren princessleia\princessleia_prisoner_pc.ghg PrincessLeia_Prisoner_PC.ghg
ren princessleia\princessleia_slave_lr_pc.ghg PrincessLeia_Slave_LR_PC.ghg
ren princessleia\princessleia_slave_pc.ghg PrincessLeia_Slave_PC.ghg
ren probedroid\probedroid.txt ProbeDroid.txt
ren probedroid\probedroid_lr_pc.ghg ProbeDroid_LR_PC.ghg
ren probedroid\probedroid_pc.ghg ProbeDroid_PC.ghg
ren protocoldroids\c3po.txt C3PO.txt
ren protocoldroids\tc14.txt TC14.txt
ren protocoldroids\c3po_lr_pc.ghg C3PO_LR_PC.ghg
ren protocoldroids\c3po_pc.ghg C3PO_PC.ghg
ren protocoldroids\tc14_lr_pc.ghg TC14_LR_PC.ghg
ren protocoldroids\tc14_pc.ghg TC14_PC.ghg
ren quigonjinn\pcclog.txt pcclog.txt
ren quigonjinn\quigonjinn.txt QuiGonJinn.txt
ren quigonjinn\quigonjinn_lr_pc.ghg QuiGonJinn_LR_PC.ghg
ren quigonjinn\quigonjinn_pc.ghg QuiGonJinn_PC.ghg
ren r2d2\r2d2.txt R2D2.txt
ren r2d2\r2q5.txt R2Q5.txt
ren r2d2\r4_p17.txt R4_P17.txt
ren r2d2\r2d2_lr_pc.ghg R2D2_LR_PC.ghg
ren r2d2\r2d2_pc.ghg R2D2_PC.ghg
ren r2d2\r2q5_lr_pc.ghg R2Q5_LR_PC.ghg
ren r2d2\r2q5_pc.ghg R2Q5_PC.ghg
ren r2d2\r4-p17_lr_pc.ghg R4-P17_LR_PC.ghg
ren r2d2\r4-p17_pc.ghg R4-P17_PC.ghg
ren r2d2\r4_p17_lr_pc.ghg R4_P17_LR_PC.ghg
ren r2d2\r4_p17_pc.ghg R4_P17_PC.ghg
ren raft\raft.txt Raft.txt
ren raft\raft_lr_pc.ghg Raft_LR_PC.ghg
ren raft\raft_pc.ghg Raft_PC.ghg
ren rancor\rancor.txt Rancor.txt
ren rancor\rancor_lr_pc.ghg Rancor_LR_PC.ghg
ren rancor\rancor_pc.ghg Rancor_PC.ghg
ren rebelscum\captainantilles.txt CaptainAntilles.txt
ren rebelscum\engineer.txt Engineer.txt
ren rebelscum\rebelfriend.txt RebelFriend.txt
ren rebelscum\rebelgeneral.txt RebelGeneral.txt
ren rebelscum\rebelhoth.txt RebelHoth.txt
ren rebelscum\rebelpilot.txt RebelPilot.txt
ren rebelscum\rebelscum.txt RebelScum.txt
ren rebelscum\captainantilles_lr_pc.ghg CaptainAntilles_LR_PC.ghg
ren rebelscum\captainantilles_pc.ghg CaptainAntilles_PC.ghg
ren rebelscum\engineer_lr_pc.ghg Engineer_LR_PC.ghg
ren rebelscum\engineer_pc.ghg Engineer_PC.ghg
ren rebelscum\rebelfriend_lr_pc.ghg RebelFriend_LR_PC.ghg
ren rebelscum\rebelfriend_pc.ghg RebelFriend_PC.ghg
ren rebelscum\rebelgeneral_lr_pc.ghg RebelGeneral_LR_PC.ghg
ren rebelscum\rebelgeneral_pc.ghg RebelGeneral_PC.ghg
ren rebelscum\rebelhoth_lr_pc.ghg RebelHoth_LR_PC.ghg
ren rebelscum\rebelhoth_pc.ghg RebelHoth_PC.ghg
ren rebelscum\rebelpilot_lr_pc.ghg RebelPilot_LR_PC.ghg
ren rebelscum\rebelpilot_pc.ghg RebelPilot_PC.ghg
ren rebelscum\rebelscum_lr_pc.ghg RebelScum_LR_PC.ghg
ren rebelscum\rebelscum_pc.ghg RebelScum_PC.ghg
ren repteer\repteer.txt RepTeer.txt
ren repteer\repteer_lr_pc.ghg RepTeer_LR_PC.ghg
ren repteer\repteer_pc.ghg RepTeer_PC.ghg
ren republicatte\republicatte.txt RepublicATTE.txt
ren republicatte\republicatte_lr_pc.ghg RepublicATTE_LR_PC.ghg
ren republicatte\republicatte_pc.ghg RepublicATTE_PC.ghg
ren republicgunship\newrepublicgunship.txt NewRepublicGunship.txt
ren republicgunship\newrepublicgunship_green.txt NewRepublicGunship_Green.txt
ren republicgunship\republicgunship.txt RepublicGunship.txt
ren republicgunship\republicgunship_green.txt RepublicGunship_Green.txt
ren republicgunship\newrepublicgunship_green_lr_pc.ghg NewRepublicGunship_Green_LR_PC.ghg
ren republicgunship\newrepublicgunship_green_pc.ghg NewRepublicGunship_Green_PC.ghg
ren republicgunship\newrepublicgunship_lr_pc.ghg NewRepublicGunship_LR_PC.ghg
ren republicgunship\newrepublicgunship_pc.ghg NewRepublicGunship_PC.ghg
ren republicgunship\republicgunship_green_lr_pc.ghg RepublicGunship_Green_LR_PC.ghg
ren republicgunship\republicgunship_green_pc.ghg RepublicGunship_Green_PC.ghg
ren republicgunship\republicgunship_lr_pc.ghg RepublicGunship_LR_PC.ghg
ren republicgunship\republicgunship_pc.ghg RepublicGunship_PC.ghg
ren robot_base\robot_base.txt Robot_Base.txt
ren robot_base\robot_base_lr_pc.ghg Robot_Base_LR_PC.ghg
ren robot_base\robot_base_pc.ghg Robot_Base_PC.ghg
ren royalguard\mawhonic.txt Mawhonic.txt
ren royalguard\rebelscum.txt RebelScum.txt
ren royalguard\royalguard.txt RoyalGuard.txt
ren royalguard\mawhonic_lr_pc.ghg Mawhonic_LR_PC.ghg
ren royalguard\mawhonic_pc.ghg Mawhonic_PC.ghg
ren royalguard\rebelscum_lr_pc.ghg RebelScum_LR_PC.ghg
ren royalguard\rebelscum_pc.ghg RebelScum_PC.ghg
ren royalguard\royalguard_lr_pc.ghg RoyalGuard_LR_PC.ghg
ren royalguard\royalguard_pc.ghg RoyalGuard_PC.ghg
ren royalnaboostarship\royalnaboostarship.txt RoyalNabooStarship.txt
ren royalnaboostarship\royalnaboostarship_lr_pc.ghg RoyalNabooStarship_LR_PC.ghg
ren royalnaboostarship\royalnaboostarship_pc.ghg RoyalNabooStarship_PC.ghg
ren royalnaboostarship\royalnaboostarship_pc.gsc RoyalNabooStarship_PC.gsc
ren sansweet\ghostbenkenobi.txt GhostBenKenobi.txt
ren sansweet\ghostbenkenobi_lr_pc.ghg GhostBenKenobi_LR_PC.ghg
ren sansweet\ghostbenkenobi_pc.ghg GhostBenKenobi_PC.ghg
ren sansweet\sansweet_lr_pc.ghg Sansweet_LR_PC.ghg
ren sansweet\sansweet_pc.ghg Sansweet_PC.ghg
ren sarlacc\sarlacc.txt Sarlacc.txt
ren sarlacc\sarlacc_lr_pc.ghg Sarlacc_LR_PC.ghg
ren sarlacc\sarlacc_pc.ghg Sarlacc_PC.ghg
ren saucer\saucer.txt Saucer.txt
ren saucer\saucer_lr_pc.ghg Saucer_LR_PC.ghg
ren saucer\saucer_pc.ghg Saucer_PC.ghg
ren sebulba\sebulba.txt Sebulba.txt
ren sebulba\sebulba_lr_pc.ghg Sebulba_LR_PC.ghg
ren sebulba\sebulba_pc.ghg Sebulba_PC.ghg
ren sebulbaspod\sebulbaspod.txt SebulbasPod.txt
ren sebulbaspod\sebulbaspod_lr_pc.ghg SebulbasPod_LR_PC.ghg
ren sebulbaspod\sebulbaspod_pc.ghg SebulbasPod_PC.ghg
ren sentrydroid\sentrydroid.txt SentryDroid.txt
ren sentrydroid\sentrydroid_lr_pc.ghg SentryDroid_LR_PC.ghg
ren sentrydroid\sentrydroid_pc.ghg SentryDroid_PC.ghg
ren service_car\service_car.txt Service_Car.txt
ren service_car\service_car_lr_pc.ghg Service_Car_LR_PC.ghg
ren service_car\service_car_pc.ghg Service_Car_PC.ghg
ren skeleton\skeleton.txt Skeleton.txt
ren skeleton\skeleton_lr_pc.ghg Skeleton_LR_PC.ghg
ren skeleton\skeleton_pc.ghg Skeleton_PC.ghg
ren skiffguard\palaceguard.txt PalaceGuard.txt
ren skiffguard\skiffguard.txt SkiffGuard.txt
ren skiffguard\palaceguard_lr_pc.ghg palaceguard_LR_PC.ghg
ren skiffguard\palaceguard_pc.ghg palaceguard_PC.ghg
ren skiffguard\skiffguard_lr_pc.ghg SkiffGuard_LR_PC.ghg
ren skiffguard\skiffguard_pc.ghg SkiffGuard_PC.ghg
ren skiffshadow\skiffshadow.txt SkiffShadow.txt
ren skiffshadow\skiffshadow_lr_pc.ghg SkiffShadow_LR_PC.ghg
ren skiffshadow\skiffshadow_pc.ghg SkiffShadow_PC.ghg
ren slave1\slave1.txt Slave1.txt
ren slave1\slave1_lr_pc.ghg Slave1_LR_PC.ghg
ren slave1\slave1_pc.ghg Slave1_PC.ghg
ren slave1\slave1_pc.gsc Slave1_PC.gsc
ren slave1_lsw1\slave1_lsw1.txt Slave1_LSW1.txt
ren slave1_lsw1\slave1_lsw1_lr_pc.ghg Slave1_LSW1_LR_PC.ghg
ren slave1_lsw1\slave1_lsw1_pc.ghg Slave1_LSW1_PC.ghg
ren snake\snake.txt Snake.txt
ren snake\snake_lr_pc.ghg Snake_LR_PC.ghg
ren snake\snake_pc.ghg Snake_PC.ghg
ren snowmob\snowmob.txt SnowMob.txt
ren snowmob\snowmob_lr_pc.ghg SnowMob_LR_PC.ghg
ren snowmob\snowmob_pc.ghg SnowMob_PC.ghg
ren snowspeeder\snowspeeder.txt Snowspeeder.txt
ren snowspeeder\snowspeeder_lr_pc.ghg Snowspeeder_LR_PC.ghg
ren snowspeeder\snowspeeder_pc.ghg Snowspeeder_PC.ghg
ren spaceman\spaceman.txt Spaceman.txt
ren spaceman\spaceman_lr_pc.ghg Spaceman_LR_PC.ghg
ren spaceman\spaceman_pc.ghg Spaceman_PC.ghg
ren speederbike\speederbike.txt SpeederBike.txt
ren speederbike\speederbike_snow.txt SpeederBike_snow.txt
ren speederbike\speederbike_lr_pc.ghg SpeederBike_LR_PC.ghg
ren speederbike\speederbike_pc.ghg SpeederBike_PC.ghg
ren speederbike\speederbike_snow_lr_pc.ghg SpeederBike_Snow_LR_PC.ghg
ren speederbike\speederbike_snow_pc.ghg SpeederBike_Snow_PC.ghg
ren speeder_dooku\speeder_dooku.txt Speeder_Dooku.txt
ren speeder_dooku\speeder_dooku_lr_pc.ghg Speeder_Dooku_LR_PC.ghg
ren speeder_dooku\speeder_dooku_pc.ghg Speeder_Dooku_PC.ghg
ren speeder_land\speeder_land.txt Speeder_Land.txt
ren speeder_land\speeder_land_lr_pc.ghg Speeder_Land_LR_PC.ghg
ren speeder_land\speeder_land_pc.ghg Speeder_Land_PC.ghg
ren stap\stap.txt STAP.txt
ren stap\stap_lr_pc.ghg STAP_LR_PC.ghg
ren stap\stap_pc.ghg STAP_PC.ghg
ren stap2\stap2.txt STAP2.txt
ren stap2\stap2_lr_pc.ghg STAP2_LR_PC.ghg
ren stap2\stap2_pc.ghg STAP2_PC.ghg
ren stormtrooper\atat_driver.txt ATAT_Driver.txt
ren stormtrooper\beachtrooper.txt BeachTrooper.txt
ren stormtrooper\deathstartrooper.txt DeathStarTrooper.txt
ren stormtrooper\imperialengineer.txt ImperialEngineer.txt
ren stormtrooper\sandtrooper.txt sandtrooper.txt
ren stormtrooper\scouttrooper.txt ScoutTrooper.txt
ren stormtrooper\snowtrooper.txt Snowtrooper.txt
ren stormtrooper\stormtrooper.txt Stormtrooper.txt
ren stormtrooper\tiefighterpilot.txt TIEFighterpilot.txt
ren stormtrooper\atat_driver_lr_pc.ghg ATAT_Driver_LR_PC.ghg
ren stormtrooper\atat_driver_pc.ghg ATAT_Driver_PC.ghg
ren stormtrooper\beachtrooper_lr_pc.ghg BeachTrooper_LR_PC.ghg
ren stormtrooper\beachtrooper_pc.ghg BeachTrooper_PC.ghg
ren stormtrooper\deathstartrooper_lr_pc.ghg DeathStarTrooper_LR_PC.ghg
ren stormtrooper\deathstartrooper_pc.ghg DeathStarTrooper_PC.ghg
ren stormtrooper\imperialengineer_lr_pc.ghg ImperialEngineer_LR_PC.ghg
ren stormtrooper\imperialengineer_pc.ghg ImperialEngineer_PC.ghg
ren stormtrooper\sandtrooper_lr_pc.ghg Sandtrooper_LR_PC.ghg
ren stormtrooper\sandtrooper_pc.ghg Sandtrooper_PC.ghg
ren stormtrooper\scouttrooper_lr_pc.ghg ScoutTrooper_LR_PC.ghg
ren stormtrooper\scouttrooper_pc.ghg ScoutTrooper_PC.ghg
ren stormtrooper\snowtrooper_lr_pc.ghg Snowtrooper_LR_PC.ghg
ren stormtrooper\snowtrooper_pc.ghg Snowtrooper_PC.ghg
ren stormtrooper\stormtrooper_lr_pc.ghg Stormtrooper_LR_PC.ghg
ren stormtrooper\stormtrooper_pc.ghg Stormtrooper_PC.ghg
ren stormtrooper\tiefighterpilot_lr_pc.ghg TIEFighterPilot_LR_PC.ghg
ren stormtrooper\tiefighterpilot_pc.ghg TIEFighterPilot_PC.ghg
ren superbattledroid\superbattledroid.txt SuperBattleDroid.txt
ren superbattledroid\superbattledroid_lr_pc.ghg SuperBattleDroid_LR_PC.ghg
ren superbattledroid\superbattledroid_pc.ghg SuperBattleDroid_PC.ghg
ren tauntaun\tauntaun.txt Tauntaun.txt
ren tauntaun\tauntaun_lr_pc.ghg Tauntaun_LR_PC.ghg
ren tauntaun\tauntaun_pc.ghg Tauntaun_PC.ghg
ren tennumb\tennumb.txt TenNumb.txt
ren tennumb\tennumb_lr_pc.ghg TenNumb_LR_PC.ghg
ren tennumb\tennumb_pc.ghg TenNumb_PC.ghg
ren theemperor\darthsidious.txt DarthSidious.txt
ren theemperor\theemperor.txt TheEmperor.txt
ren theemperor\darthsidious_lr_pc.ghg DarthSidious_LR_PC.ghg
ren theemperor\darthsidious_pc.ghg DarthSidious_PC.ghg
ren theemperor\theemperor_lr_pc.ghg TheEmperor_LR_PC.ghg
ren theemperor\theemperor_pc.ghg TheEmperor_PC.ghg
ren thermaldetonator\thermaldetonator_lr_pc.ghg ThermalDetonator_LR_PC.ghg
ren thermaldetonator\thermaldetonator_pc.ghg ThermalDetonator_PC.ghg
ren tiebomber\tiebomber.txt TIEBomber.txt
ren tiebomber\tiebomber_lr_pc.ghg TIEBomber_LR_PC.ghg
ren tiebomber\tiebomber_pc.ghg TIEBomber_PC.ghg
ren tiefighter\tiefighter.txt TIEFighter.txt
ren tiefighter\tiefighter_lr_pc.ghg TIEFighter_LR_PC.ghg
ren tiefighter\tiefighter_pc.ghg TIEFighter_PC.ghg
ren tiefighterdarth\tiefighterdarth.txt TIEFighterDarth.txt
ren tiefighterdarth\tiefighterdarth_lr_pc.ghg TIEFighterDarth_LR_PC.ghg
ren tiefighterdarth\tiefighterdarth_pc.ghg TIEFighterDarth_PC.ghg
ren tieinterceptor\tieinterceptor.txt TIEInterceptor.txt
ren tieinterceptor\tieinterceptor_lr_pc.ghg TIEInterceptor_LR_PC.ghg
ren tieinterceptor\tieinterceptor_pc.ghg TIEInterceptor_PC.ghg
ren towncar\towncar.txt TownCar.txt
ren towncar\towncar_lr_pc.ghg TownCar_LR_PC.ghg
ren towncar\towncar_pc.ghg TownCar_PC.ghg
ren tractor\tractor.txt Tractor.txt
ren tractor\tractor_lr_pc.ghg Tractor_LR_PC.ghg
ren tractor\tractor_pc.ghg Tractor_PC.ghg
ren tradefederationlandingship\tradefederationlandingship.txt TradeFederationLandingShip.txt
ren tradefederationlandingship\tradefederationlandingship_lr_pc.ghg TradeFederationLandingShip_LR_PC.ghg
ren tradefederationlandingship\tradefederationlandingship_pc.ghg TradeFederationLandingShip_PC.ghg
ren trainingremote\trainingremote.txt TrainingRemote.txt
ren trainingremote\trainingremote_lr_pc.ghg TrainingRemote_LR_PC.ghg
ren trainingremote\trainingremote_pc.ghg TrainingRemote_PC.ghg
ren troopercannon\troopercannon.txt TrooperCannon.txt
ren troopercannon\troopercannon_lr_pc.ghg TrooperCannon_LR_PC.ghg
ren troopercannon\troopercannon_pc.ghg TrooperCannon_PC.ghg
ren tuskenraider\tuskenraider.txt TuskenRaider.txt
ren tuskenraider\tuskenraider_lr_pc.ghg TuskenRaider_LR_PC.ghg
ren tuskenraider\tuskenraider_pc.ghg TuskenRaider_PC.ghg
ren ugnaught\ugnaught.txt Ugnaught.txt
ren ugnaught\ugnaught_lr_pc.ghg Ugnaught_LR_PC.ghg
ren ugnaught\ugnaught_pc.ghg Ugnaught_PC.ghg
ren vulturedroid\vulturedroid.txt VultureDroid.txt
ren vulturedroid\vulturedroid_lr_pc.ghg VultureDroid_LR_PC.ghg
ren vulturedroid\vulturedroid_pc.ghg VultureDroid_PC.ghg
ren vulturedroid\vulturedroid_pc.gsc VultureDroid_PC.gsc
ren wa7\wa7.txt WA7.txt
ren wa7\wa7_lr_pc.ghg WA7_LR_PC.ghg
ren wa7\wa7_pc.ghg WA7_PC.ghg
ren wampa\wampa.txt Wampa.txt
ren wampa\wampa_lr_pc.ghg Wampa_LR_PC.ghg
ren wampa\wampa_pc.ghg Wampa_PC.ghg
ren watto\watto.txt Watto.txt
ren watto\watto_lr_pc.ghg Watto_LR_PC.ghg
ren watto\watto_pc.ghg Watto_PC.ghg
ren weirdo\benkenobi.txt BenKenobi.txt
ren weirdo\ghost.txt Ghost.txt
ren weirdo\weirdo1.txt Weirdo1.txt
ren weirdo\weirdo2.txt Weirdo2.txt
ren weirdo\ghost_lr_pc.ghg Ghost_LR_PC.ghg
ren weirdo\ghost_pc.ghg Ghost_PC.ghg
ren weirdo\weirdo1_lr_pc.ghg Weirdo1_LR_PC.ghg
ren weirdo\weirdo1_pc.ghg Weirdo1_PC.ghg
ren weirdo\weirdo2_lr_pc.ghg Weirdo2_LR_PC.ghg
ren weirdo\weirdo2_pc.ghg Weirdo2_PC.ghg
ren wheelbike\wheelbike.txt WheelBike.txt
ren wheelbike\wheelbike_lr_pc.ghg WheelBike_LR_PC.ghg
ren wheelbike\wheelbike_pc.ghg WheelBike_PC.ghg
ren whip\whip.txt Whip.txt
ren whip\whip_lr_pc.ghg Whip_LR_PC.ghg
ren whip\whip_pc.ghg Whip_PC.ghg
ren womprat\womprat.txt WompRat.txt
ren womprat\womprat_lr_pc.ghg WompRat_LR_PC.ghg
ren womprat\womprat_pc.ghg WompRat_PC.ghg
ren wookieflyer\wookieflyer.txt WookieFlyer.txt
ren wookieflyer\wookieflyer_lr_pc.ghg WookieFlyer_LR_PC.ghg
ren wookieflyer\wookieflyer_pc.ghg WookieFlyer_PC.ghg
ren worm\worm.txt Worm.txt
ren worm\worm_lr_pc.ghg Worm_LR_PC.ghg
ren worm\worm_pc.ghg Worm_PC.ghg
ren xwing\xwing.txt XWing.txt
ren xwing\xwing_lr_pc.ghg XWing_LR_PC.ghg
ren xwing\xwing_pc.ghg XWing_PC.ghg
ren yoda\yoda.txt Yoda.txt
ren yoda\yoda_ghost.txt Yoda_Ghost.txt
ren yoda\yoda_ghost_lr_pc.ghg Yoda_Ghost_LR_PC.ghg
ren yoda\yoda_ghost_pc.ghg Yoda_Ghost_PC.ghg
ren yoda\yoda_lr_pc.ghg Yoda_LR_PC.ghg
ren yoda\yoda_pc.ghg Yoda_PC.ghg
ren ywing\ywing.txt YWing.txt
ren ywing\ywing_lr_pc.ghg YWing_LR_PC.ghg
ren ywing\ywing_pc.ghg YWing_PC.ghg
ren zamdroid\zamdroid.txt ZamDroid.txt
ren zamdroid\zamdroid_lr_pc.ghg ZamDroid_LR_PC.ghg
ren zamdroid\zamdroid_pc.ghg ZamDroid_PC.ghg
ren zamsspeeder\zamsspeeder.txt ZamsSpeeder.txt
ren zamsspeeder\zamsspeeder_old.txt ZamsSpeeder_old.txt
ren zamsspeeder\zamsspeeder_lr_pc.ghg ZamsSpeeder_LR_PC.ghg
ren zamsspeeder\zamsspeeder_pc.ghg ZamsSpeeder_PC.ghg
ren zamwesell\zamwesell.txt ZamWesell.txt 
ren zamwesell\zamsspeeder_lr_pc.ghg ZamsSpeeder_LR_PC.ghg
ren zamwesell\zamsspeeder_pc.ghg ZamsSpeeder_PC.ghg
ren zamwesell\zamwesell_lr_pc.ghg ZamWesell_LR_PC.ghg
ren zamwesell\zamwesell_pc.ghg ZamWesell_PC.ghg

cd ..